import {
  type CashbackLinkedCardsQuery,
  type Category,
  type GetCashbackOffersGroupByAdvertiserQuery,
  type GetFeaturedOffersQuery,
  type GetInstoreOffersByAdvertiserIdQuery,
  type InStoreOffer,
  OfferType,
  type OnlineOffer,
} from '../../generated';
import type {
  CashbackEmploymentHeroProviderIdQuery,
  CashbackUserInfoQuery,
  CashbackUserTokenQuery,
} from '../../../graphql/generated';
import { AutoEnrolStatus, BankLinkedStatus } from '../../../graphql/generated';

export const mockCashbackUserToken: CashbackUserTokenQuery = {
  cashbackUserToken: {
    key: '1234',
    token: '1234',
  },
};

export const mockCashbackUserInfo: CashbackUserInfoQuery = {
  cashbackUserInfo: {
    __typename: 'CashbackUserInfo',
    autoEnrolMessage: 'SUCCESS',
    autoEnrolStatus: AutoEnrolStatus.Success,
    bankLinkedMessage: 'SUCCESS',
    bankLinkedStatus: BankLinkedStatus.Success,
  },
};

export const mockCashbackEHProviderId: CashbackEmploymentHeroProviderIdQuery = {
  cashbackEmploymentHeroProviderId: '1234',
};

export const mockOnlineOffer: OnlineOffer = {
  about: 'About Offer',
  advertiserId: '1234',
  advertiserAbout: 'About Advertiser',
  advertiserName: 'Gourmet Basket',
  cashback: 'cashback',
  categoryCode: '1',
  createdAt: '',
  description:
    'Click the link above to access 8% Cashback on your purchases. You will receive an email confirming your pending Cashback as soon as PokitPal receives confirmation of your purchase from the retailer. Allow up to 7 days from the date of your purchase. Depending on the retailers returns policy, allow approximately 90 days for the cashback to be deposited into your personal MyWallet.',
  howItWorks:
    'To receive Cashback on your purchases, click the button provided to access the retailer’s website. When you’ve finished shopping, you will receive a notification in your app confirming the Cashback amount due. If you have not received a notification within 5 days from the date of your online purchase, please let us know. Depending on the retailers returns policy, it may take up to 90 days for the Cashback to be settled and deposited in your personal Wallet.',
  id: '12323',
  imageUrl:
    'https://pokitpal-images.s3-ap-southeast-2.amazonaws.com/stage/UploadFiles/CoverShot/advertiser_cover_image.1652861436_1652861436.Jpeg',
  isCardLinkedOffer: false,
  logoUrl:
    'https://pokitpal-images.s3-ap-southeast-2.amazonaws.com/stage/UploadFiles/Logos/advertiser_logo.1652861436_1652861436.Jpeg',
  popularScore: 0,
  title: '8% Cashback on All Purchases',
  tnc: 'To be eligible for Cashback you must access the partner site through the link above. GST, delivery costs and products that are returned do not contribute to the purchase amount that is eligible for Cashback.',
  trackingUrl: 'trackingUrl',
  type: OfferType.Online,
  updatedAt: '',
};

export const mockInstoreOffer: InStoreOffer = {
  __typename: 'InStoreOffer',
  id: '919929',
  title: 'Up to 4% Cashback',
  logoUrl:
    'https://pokitpal-images.s3-ap-southeast-2.amazonaws.com/stage/UploadFiles/Logos/advertiser_logo.1627433652_1627433652.Jpeg',
  imageUrl:
    'https://pokitpal-images.s3-ap-southeast-2.amazonaws.com/stage/UploadFiles/CoverShot/advertiser_cover_image.1627433652_1627433652.Jpeg',
  advertiserId: '1234',
  advertiserName: 'Novo Shoes',
  categoryCode: '3',
  website: '',
  latitude: -33.871722,
  longitude: 151.2067078,
  tnc: 'Virgin Money reserves the right to amend or withdraw this offer at any time without notice. Offer expires midnight 30/06/2022 AEST, is valid at standalone stores only when payment is made using your Virgin Money Debit Visa Card. Offer cannot be used in conjunction with any other offer. Excludes voucher codes, gift cards, cash back and coupon deals.',
  description: '',
  howItWorks:
    'Earn 8 Virgin Money Points for every $1 you spend with no minimum spend required. To be eligible, shop at participating venues with your Virgin Money Visa Debit Card. Your points will be credited to your Virgin Money Rewards account once we confirm your purchase. Allow up to 5 business days from the date of transaction for the points to be credited to your account.',
  popularScore: 4.0,
  cashback: '4%',
  address: 'dasd',
  offerId: '312312',
  advertiserAbout: '',
  createdAt: '',
  endDate: '',
  phone: '',
  startDate: '',
  type: OfferType.Instore,
  updatedAt: '',
};

export const mockCashbackCategories: Array<Category> = [
  {
    name: 'Dining',
    categoryCode: 'dining',
    imageUrl: '',
  },
  {
    name: 'Fashion',
    categoryCode: 'fashion',
    imageUrl: '',
  },
  {
    name: 'Fitness',
    categoryCode: 'fitness',
    imageUrl: '',
  },
  {
    name: 'Wellness',
    categoryCode: 'wellness',
    imageUrl: '',
  },
  {
    name: 'Retail',
    categoryCode: 'retail',
    imageUrl: '',
  },
  {
    name: 'Travel',
    categoryCode: 'travel',
    imageUrl: '',
  },
  {
    name: 'Tech',
    categoryCode: 'tech',
    imageUrl: '',
  },
  {
    name: 'Finance',
    categoryCode: 'finance',
    imageUrl: '',
  },
  {
    name: 'Experiences',
    categoryCode: 'experiences',
    imageUrl: '',
  },
];

export const mockFeaturedOffersData: GetFeaturedOffersQuery = {
  me: {
    cashback: {
      featuresOffers: {
        edges: [
          {
            node: {
              id: '919645',
              type: OfferType.Online,
              categoryCode: 'fashion',
              title: '7.5% Cashback on All Purchases',
              description:
                'Shein prides itself on offering on-trend styles catering to both young women and teens, that won’t break the bank. It revolves around the concept that "everyone can enjoy the beauty of fashion". \n\n',
              cashback: '7.5%',
              imageUrl:
                'https://pokitpal-images.s3-ap-southeast-2.amazonaws.com/stage/UploadFiles/CoverShot/advertiser-da104e04-8b5b-4664-97db-c7cc938efabb.jpg',
              logoUrl:
                'https://pokitpal-images.s3-ap-southeast-2.amazonaws.com/stage/UploadFiles/Logos/advertiser-def13e02-c3fd-4d11-802b-d4392f666c83.jpg',
              trackingUrl: '',
              howItWorks:
                'To be eligible for Cashback you must access the partner site through the link provided in this application.\n\nGST, delivery costs and products that are returned do not contribute to the purchase amount that is eligible for Cashback. You are unable to claim the offer if you use a payment platform such as Afterpay, Zip or Paypal. Cashback will be credited to your e-wallet within 3 days of receipt of payment but may remain in a Pending status until the returns period is closed.',
              tnc: 'To be eligible for Cashback you must access the partner site through the button / link provided. No Cashback on Gift Card Purchases.\n',
              about:
                'SHEIN is an international fast fashion company focusing on apparel for women, with contemporary designs and affordable pricing. We offer thousands of styles for all body shapes and sizes, which are all updated frequently with hundreds of new products every week.',
              advertiserId: '1',
              advertiserName: 'Shein',
              advertiserAbout: '',
              isCardLinkedOffer: false,
              popularScore: 0,
              createdAt: '2022-10-06T00:59:35Z',
              updatedAt: '2024-01-08T08:28:19Z',
            },
          },
          {
            node: {
              id: '919648',
              type: OfferType.Online,
              categoryCode: 'fashion',
              title: '5% Cashback on All Purchases',
              description:
                'General Pants is all about the hottest global trends, brands and products for young-blooded individuals. Their up-to-the-minute affordable threads are sourced both locally and globally.\n',
              cashback: '5%',
              imageUrl:
                'https://pokitpal-images.s3-ap-southeast-2.amazonaws.com/stage/UploadFiles/CoverShot/advertiser_cover_image.1652753114_1652753114.Jpeg',
              logoUrl:
                'https://pokitpal-images.s3-ap-southeast-2.amazonaws.com/stage/UploadFiles/Logos/advertiser-9d534192-7078-49bf-97e0-bbdc1caa84cb.jpg',
              trackingUrl: '',
              howItWorks:
                'To be eligible for Cashback you must access the partner site through the link provided in this application.\n\nGST, delivery costs and products that are returned do not contribute to the purchase amount that is eligible for Cashback. You are unable to claim the offer if you use a payment platform such as Afterpay, Zip or Paypal. Cashback will be credited to your e-wallet within 3 days of receipt of payment but may remain in a Pending status until the returns period is closed.',
              tnc: 'To be eligible for Cashback you must access the partner site through the button / link provided. GST, delivery costs and products that are returned do not contribute to the purchase amount that is eligible for Cashback. No Cashback on Gift Card Purchases.',
              about: '',
              advertiserId: '2',
              advertiserName: 'General Pants Co.',
              advertiserAbout: '',
              isCardLinkedOffer: false,
              popularScore: 0,
              createdAt: '2022-10-06T01:00:09Z',
              updatedAt: '2024-01-08T08:28:19Z',
            },
          },
          {
            node: {
              id: '919653',
              type: OfferType.Online,
              categoryCode: 'others',
              title: '6% Cashback on All Purchases',
              description:
                'If you’re looking for sleek and stylish designer glasses or sunglasses to upgrade any look, then you won’t be disappointed with what’s on offer at 1001 Optical. \n\nShop big names such as Ray-Ban, Prada, Tom Ford, Oakley, Gucci and many more. ',
              cashback: '6%',
              imageUrl:
                'https://pokitpal-images.s3-ap-southeast-2.amazonaws.com/stage/UploadFiles/CoverShot/advertiser-9f553d7f-d517-4268-a09e-8d6b7fa5521d.jpg',
              logoUrl:
                'https://pokitpal-images.s3-ap-southeast-2.amazonaws.com/stage/UploadFiles/Logos/advertiser-0d277746-39d1-48e2-8f7b-144ab894ee80.jpg',
              trackingUrl: '',
              howItWorks:
                'To be eligible for Cashback you must access the partner site through the link provided in this application.\n\nGST, delivery costs and products that are returned do not contribute to the purchase amount that is eligible for Cashback. You are unable to claim the offer if you use a payment platform such as Afterpay, Zip or Paypal. Cashback will be credited to your e-wallet within 3 days of receipt of payment but may remain in a Pending status until the returns period is closed.',
              tnc: 'To be eligible for Cashback you must access the partner site through the button / link provided. No Cashback on Gift Card Purchases.\n',
              about: 'about',
              advertiserId: '3',
              advertiserName: '1001 Optical',
              advertiserAbout: '',
              isCardLinkedOffer: false,
              popularScore: 0,
              createdAt: '2022-10-06T01:01:04Z',
              updatedAt: '2024-01-08T08:28:19Z',
            },
          },
          {
            node: {
              id: '919654',
              type: OfferType.Online,
              categoryCode: 'fitness',
              title: '7.5% Cashback on All Purchases',
              description: 'Click the link above to access 7.5% Cashback on your purchases.',
              cashback: '7.5%',
              imageUrl:
                'https://pokitpal-images.s3-ap-southeast-2.amazonaws.com/stage/UploadFiles/CoverShot/advertiser-1a7d52a6-d04c-4da5-af30-28ba8967787c.jpg',
              logoUrl:
                'https://pokitpal-images.s3-ap-southeast-2.amazonaws.com/stage/UploadFiles/Logos/advertiser-f410b99b-866d-4644-a45e-d562606a8dfd.jpg',
              trackingUrl: '',
              howItWorks:
                'To be eligible for Cashback you must access the partner site through the link provided in this application',
              tnc: '',
              about:
                'Established in 1948, Puma shoes are a celebration of some of the greatest athletes and their legendary performances from around the world, over the years Puma shoes have evolved into a household name for on-trend, high performance footwear.',
              advertiserId: '4',
              advertiserName: 'Puma',
              advertiserAbout: '',
              isCardLinkedOffer: false,
              popularScore: 0,
              createdAt: '2022-10-06T01:01:11Z',
              updatedAt: '2024-01-08T08:28:19Z',
            },
          },
          {
            node: {
              id: '919655',
              type: OfferType.Online,
              categoryCode: 'fashion',
              title: '3% Cashback on All Purchases',
              description:
                "BooHoo is young, inclusive brand - think of us as your fashion best friend. A global brand that doesn't sleep",
              cashback: '3%',
              imageUrl:
                'https://pokitpal-images.s3-ap-southeast-2.amazonaws.com/stage/UploadFiles/CoverShot/advertiser-3d97dd17-c1ff-48bf-a657-f575b64151ab.jpg',
              logoUrl:
                'https://pokitpal-images.s3-ap-southeast-2.amazonaws.com/stage/UploadFiles/Logos/advertiser-b44e628b-c65c-4aba-9018-977da6ebc4cb.jpg',
              trackingUrl: '',
              howItWorks: '',
              tnc: '',
              about: '',
              advertiserId: '5',
              advertiserName: 'Boohoo',
              advertiserAbout: '',
              isCardLinkedOffer: false,
              popularScore: 0,
              createdAt: '2022-10-06T01:01:20Z',
              updatedAt: '2024-01-08T08:28:19Z',
            },
          },
          {
            node: {
              id: '919656',
              type: OfferType.Online,
              categoryCode: 'fashion',
              title: '3% Cashback on All Purchases',
              description:
                "BooHoo is young, inclusive brand - think of us as your fashion best friend. A global brand that doesn't sleep",
              cashback: '3%',
              imageUrl:
                'https://pokitpal-images.s3-ap-southeast-2.amazonaws.com/stage/UploadFiles/CoverShot/advertiser-3d97dd17-c1ff-48bf-a657-f575b64151ab.jpg',
              logoUrl:
                'https://pokitpal-images.s3-ap-southeast-2.amazonaws.com/stage/UploadFiles/Logos/advertiser-b44e628b-c65c-4aba-9018-977da6ebc4cb.jpg',
              trackingUrl: '',
              howItWorks: '',
              tnc: '',
              about: '',
              advertiserId: '6',
              advertiserName: 'Boohoo',
              advertiserAbout: '',
              isCardLinkedOffer: false,
              popularScore: 0,
              createdAt: '2022-10-06T01:01:20Z',
              updatedAt: '2024-01-08T08:28:19Z',
            },
          },
          {
            node: {
              id: '919700',
              type: OfferType.Online,
              categoryCode: 'travel',
              title: '10% Cashback on All Purchases',
              description:
                'Travello is dedicated in finding extraordinary tours from around the world by building relationships with local tour operators who share our values. We ensure that all our partners are passionate about offering unique experiences while being aware of their impact on the environment.\n',
              cashback: '3%',
              imageUrl:
                'https://pokitpal-images.s3-ap-southeast-2.amazonaws.com/stage/UploadFiles/CoverShot/advertiser-7f5dd9e8-633c-4dda-8682-9dbe1114c558.jpg',
              logoUrl:
                'https://pokitpal-images.s3-ap-southeast-2.amazonaws.com/stage/UploadFiles/Logos/advertiser-b44e628b-c65c-4aba-9018-977da6ebc4cb.jpg',
              trackingUrl: '',
              howItWorks: '',
              tnc: '',
              about: '',
              advertiserId: '7',
              advertiserName: 'Booking.com',
              advertiserAbout: 'About Us goes here.',
              isCardLinkedOffer: false,
              popularScore: 0,
              createdAt: '2022-10-06T01:01:20Z',
              updatedAt: '2024-01-08T08:28:19Z',
            },
          },
        ],
        pageInfo: {
          hasNextPage: false,
          endCursor: null,
          totalCount: null,
          totalPages: null,
        },
      },
    },
  },
};

export const mockInstoreOffersByAdvertiserId = {
  me: {
    cashback: {
      instoreOffersByAdvertiserId: {
        offers: [
          {
            id: '919647',
            type: 'INSTORE',
            offerId: '919647',
            title: '6% Cashback on All Purchases',
            description:
              "Forever New is a women's fashion clothing and accessories brand founded in Melbourne, Australia. Emerging in 2006, Forever New is one of the fastest growing Australian brands and is synonymous with quality fashion and a uniquely beautiful style.",
            cashback: '6%',
            categoryCode: 'fashion',
            howItWorks:
              'To receive Cashback on your purchases, shop at participating venues with your card linked to your account. When you’ve finished shopping, you will receive a notification in your app confirming the Cashback amount due. If you have not received a notification within 5 days from the date of your purchase, please let us know. Depending on the retailer’s returns policy, it may take up to 90 days for the Cashback to be settled and deposited in your personal Wallet.\n',
            imageUrl:
              'https://pokitpal-images.s3-ap-southeast-2.amazonaws.com/stage/UploadFiles/CoverShot/advertiser-76a0f34c-80b4-40c6-9bc8-b033051e0fa7.jpg',
            logoUrl:
              'https://pokitpal-images.s3-ap-southeast-2.amazonaws.com/stage/UploadFiles/Logos/advertiser-cf764b91-ff4a-4286-85e1-0f5757be2b19.jpg',
            advertiserName: 'Forever New Instore',
            advertiserAbout:
              "Forever New is a women's fashion clothing and accessories brand founded in Melbourne, Australia. Emerging in 2006, Forever New is one of the fastest growing Australian brands and is synonymous with quality fashion and a uniquely beautiful style.",
            tnc: 'You must complete a transaction using the card linked to your account. Excludes voucher codes, gift cards, cash back and coupon deals.\n',
            website: '',
            phone: '',
            locations: [
              {
                locationId: '927795',
                address: 'SHOP 229A CASUARINA S/C, CASUARINA, NT, 810',
                latitude: -12.374391,
                longitude: 130.881721,
              },
              {
                locationId: '927796',
                address: 'World Square Sydney, Sydney, NSW, 2000',
                latitude: -33.877181,
                longitude: 151.206879,
              },
              {
                locationId: '927797',
                address: 'Tenancy L00.66, Sydney, NSW, 2000',
                latitude: -33.869664,
                longitude: 151.207398,
              },
              {
                locationId: '927798',
                address: 'Shop 2031/2 Westfield Bondi, Bondi Junction, NSW, 2022',
                latitude: -33.892699,
                longitude: 151.250385,
              },
              {
                locationId: '927799',
                address: 'SHOP 141-152, EASTGARDENS, NSW, 2036',
                latitude: -33.944826,
                longitude: 151.224329,
              },
              {
                locationId: '927800',
                address: 'Shop 205 Birkenhead Pt, Drummoyne, NSW, 2047',
                latitude: -33.855523,
                longitude: 151.161854,
              },
              {
                locationId: '927801',
                address: 'Shop 416/7 1 Anderson Street, Chatswood, NSW, 2067',
                latitude: -33.79735,
                longitude: 151.183117,
              },
              {
                locationId: '927802',
                address: 'Shop 1508 Warringah Mall S/C, Brookvale, NSW, 2100',
                latitude: -33.767587,
                longitude: 151.266031,
              },
              {
                locationId: '927803',
                address: 'T3365 Macquarie Shopping Cnt, North Ryde, NSW, 2113',
                latitude: -33.776719,
                longitude: 151.120517,
              },
              {
                locationId: '927804',
                address: 'Shop 226/27,, Burwood, NSW, 2134',
                latitude: -33.874984,
                longitude: 151.106278,
              },
              {
                locationId: '927805',
                address: 'Shop 3089-3091 West Point S/C, BLACKTOWN, NSW, 2148',
                latitude: -33.77023,
                longitude: 150.905453,
              },
              {
                locationId: '927806',
                address: 'Westfield Parramatta, Parramatta, NSW, 2150',
                latitude: -33.817252,
                longitude: 151.001338,
              },
              {
                locationId: '927807',
                address: 'T390 Castle Towers, Castle Hill, NSW, 2154',
                latitude: -33.730484,
                longitude: 151.005372,
              },
              {
                locationId: '927808',
                address: 'SHOP 150 ROUSE HILL TOWN CT, ROUSE HILL, NSW, 2155',
                latitude: -33.690433,
                longitude: 150.924072,
              },
              {
                locationId: '927809',
                address: 'Tenancy 256, 581-583 Polding, WETHERILL PARK, NSW, 2164',
                latitude: -33.858079,
                longitude: 150.898283,
              },
              {
                locationId: '927810',
                address: 'Westfield Liverpool, Liverpool, NSW, 2170',
                latitude: -33.919004,
                longitude: 150.924152,
              },
              {
                locationId: '927811',
                address: 'Shop ML 70 Bankstown Centro, Bankstown, NSW, 2200',
                latitude: -33.916523,
                longitude: 151.038488,
              },
              {
                locationId: '927812',
                address: 'Cnr Cross St and Park Rd, Hurstville, NSW, 2220',
                latitude: -33.966169,
                longitude: 151.105196,
              },
              {
                locationId: '927813',
                address: 'Shop 3027/28/29 - Westfield, Miranda, NSW, 2228',
                latitude: -34.03496,
                longitude: 151.100174,
              },
              {
                locationId: '927814',
                address: 'Shop T217, Erina, NSW, 2250',
                latitude: -33.437724,
                longitude: 151.393336,
              },
              {
                locationId: '927815',
                address: 'Tenancy L01 1023/4, Charlestown, NSW, 2290',
                latitude: -32.964091,
                longitude: 151.693623,
              },
              {
                locationId: '927816',
                address: 'Shop R01001 Crown St Mall, Wollongong, NSW, 2500',
                latitude: -34.424659,
                longitude: 150.894195,
              },
              {
                locationId: '927817',
                address: 'SHOP 227 Lake Entrance Road, Shellharbour, NSW, 2529',
                latitude: -34.564167,
                longitude: 150.839137,
              },
              {
                locationId: '927818',
                address: 'SHOP 067 200 GILCHRIST DRIVE, CAMPBELLTOWN, NSW, 2560',
                latitude: -34.074829,
                longitude: 150.797835,
              },
              {
                locationId: '927819',
                address: 'Tenancy 154, Narellan, NSW, 2567',
                latitude: -34.042679,
                longitude: 150.736742,
              },
              {
                locationId: '927820',
                address: 'Shop EF20, Canberra, ACT, 2601',
                latitude: -35.2788,
                longitude: 149.133442,
              },
              {
                locationId: '927821',
                address: 'Shop T34 Albury Myer Cntrpoint, Albury, NSW, 2640',
                latitude: -36.080149,
                longitude: 146.919837,
              },
              {
                locationId: '927822',
                address: 'Tenancy G.06 Wagga Wagga, Wagga Wagga, NSW, 2650',
                latitude: -35.115158,
                longitude: 147.371148,
              },
              {
                locationId: '927823',
                address: 'Westfield Penrith, Penrith, NSW, 2750',
                latitude: -33.751489,
                longitude: 150.693107,
              },
              {
                locationId: '927824',
                address: 'Shop 161-164 Melbourne Central, Melbourne, VIC, 3000',
                latitude: -37.811619,
                longitude: 144.963779,
              },
              {
                locationId: '927825',
                address: 'Shop T67, Level 1 Spencer St, Melbourne, VIC, 3000',
                latitude: -37.816009,
                longitude: 144.952131,
              },
              {
                locationId: '927826',
                address: 'Tenancy 126, Whiteman St, Southbank, VIC, 3006',
                latitude: -37.824836,
                longitude: 144.9583,
              },
              {
                locationId: '927827',
                address: 'Shop 7South Wharf Retail Tena, Southbank, VIC, 3006',
                latitude: -37.824961,
                longitude: 144.950152,
              },
              {
                locationId: '927828',
                address: 'Tenancy 234 Werribee Plaza, Werribee, VIC, 3030',
                latitude: -37.876469,
                longitude: 144.680944,
              },
              {
                locationId: '927829',
                address: 'T 3550,120-200 Rosamond Rd, Maribyrnong, VIC, 3032',
                latitude: -37.773686,
                longitude: 144.888786,
              },
              {
                locationId: '927830',
                address: 'Tenancy 165A, Watergardens, Taylors Lakes, VIC, 3038',
                latitude: -37.699299,
                longitude: 144.775746,
              },
              {
                locationId: '927831',
                address: 'Shop E00-13, Craigieburn Cntrl, Craigieburn, VIC, 3064',
                latitude: -37.592899,
                longitude: 144.913627,
              },
              {
                locationId: '927832',
                address: 'Tenancy G10 - Northland Shopping, Preston, VIC, 3072',
                latitude: -37.738523,
                longitude: 145.03003,
              },
              {
                locationId: '927833',
                address: 'Shop 206,Cnr Cooper & High St, Epping, VIC, 3076',
                latitude: -37.6536,
                longitude: 145.017484,
              },
              {
                locationId: '927834',
                address: 'L03 Shop 369 Greensborough, Greensborough, VIC, 3088',
                latitude: -37.702509,
                longitude: 145.102822,
              },
              {
                locationId: '927835',
                address: 'Shop T138 Westfield Doncaster, Doncaster, VIC, 3108',
                latitude: -37.785464,
                longitude: 145.126216,
              },
              {
                locationId: '927836',
                address: 'Tenancy 2123 - Eastland Shopping, Ringwood, VIC, 3134',
                latitude: -37.812682,
                longitude: 145.22917,
              },
              {
                locationId: '927837',
                address: 'Tenancy G94 Chadstone, Chadstone, VIC, 3148',
                latitude: -37.886277,
                longitude: 145.08295,
              },
              {
                locationId: '927838',
                address: 'Shop 1077,425 Burwood Highway, Wantirna South, VIC, 3152',
                latitude: -37.869056,
                longitude: 145.241375,
              },
              {
                locationId: '927839',
                address: 'Shop 2087,1239 Nepean Highway, Cheltenham, VIC, 3192',
                latitude: -37.95887,
                longitude: 145.055309,
              },
              {
                locationId: '927840',
                address: 'Shop 120, 28 Beach Street, Frankston, VIC, 3199',
                latitude: -38.141806,
                longitude: 145.124071,
              },
              {
                locationId: '927841',
                address: 'Shop No. 84 Market Square S/C, Geelong, VIC, 3220',
                latitude: -38.147987,
                longitude: 144.361684,
              },
              {
                locationId: '927842',
                address: 'Tenancy 111, Wendouree, VIC, 3355',
                latitude: -37.534308,
                longitude: 143.8245,
              },
              {
                locationId: '927843',
                address: 'Shop 1107/71, Fountain Gate, VIC, 3805',
                latitude: -38.017395,
                longitude: 145.304118,
              },
              {
                locationId: '927844',
                address: 'Tenancy SP108 Cranbourne Park, Cranbourne, VIC, 3977',
                latitude: -38.109625,
                longitude: 145.281926,
              },
              {
                locationId: '927845',
                address: 'Shop 1, The Pavilion, Brisbane, QLD, 4000',
                latitude: -27.46974,
                longitude: 153.024918,
              },
              {
                locationId: '927846',
                address: 'Shop 1-2659 Zone B Level 2,, Chermside, QLD, 4032',
                latitude: -27.383874,
                longitude: 153.032517,
              },
              {
                locationId: '927847',
                address: 'Tenancy 2092 Indooroopilly SC, Indooroopilly, QLD, 4068',
                latitude: -27.499136,
                longitude: 152.972682,
              },
              {
                locationId: '927848',
                address: 'Shop 25 Mt. Ommaney Centre, Mt Ommaney, QLD, 4074',
                latitude: -27.547926,
                longitude: 152.939687,
              },
              {
                locationId: '927849',
                address: 'SHOP 2113 - WESTFIELD, Upper Mt Gravatt, QLD, 4122',
                latitude: -27.562952,
                longitude: 153.081055,
              },
              {
                locationId: '927850',
                address: 'Shop 2210 Westfield Carindale, Carindale, QLD, 4152',
                latitude: -27.501856,
                longitude: 153.10196,
              },
              {
                locationId: '927851',
                address: 'Shop C45A Harbour Town, Biggera Waters, QLD, 4216',
                latitude: -27.931344,
                longitude: 153.38808,
              },
              {
                locationId: '927852',
                address: 'Tenancy 333 Pacific Fair, Broadbeach, QLD, 4218',
                latitude: -28.03638,
                longitude: 153.42931,
              },
              {
                locationId: '927853',
                address: 'Shop 4289, Robina Town Centre, Robina, QLD, 4226',
                latitude: -28.078175,
                longitude: 153.384576,
              },
              {
                locationId: '927854',
                address: 'Tenancy 252, Springfield Lakes, QLD, 4300',
                latitude: -27.677621,
                longitude: 152.902152,
              },
              {
                locationId: '927855',
                address: 'Tenancy 2102/3, Toowoomba, QLD, 4350',
                latitude: -27.561416,
                longitude: 151.950418,
              },
              {
                locationId: '927856',
                address: 'Shop 1232, North Lakes, QLD, 4509',
                latitude: -27.241076,
                longitude: 153.016864,
              },
              {
                locationId: '927857',
                address: 'Shop No. 377B Sunshine Plaza, Maroochydore, QLD, 4558',
                latitude: -26.65476,
                longitude: 153.089056,
              },
              {
                locationId: '927858',
                address: 'SHOP 247/248 STOCKLANDS, ROCKHAMPTON, QLD, 4700',
                latitude: -29.433221,
                longitude: 153.340624,
              },
              {
                locationId: '927859',
                address: 'Caneland Central, Ground Flr, Mackay, QLD, 4740',
                latitude: -21.138258,
                longitude: 149.178053,
              },
              {
                locationId: '927860',
                address: '310 Ross River Rd, Aitkenvale, QLD, 4814',
                latitude: -19.299238,
                longitude: 146.763076,
              },
              {
                locationId: '927861',
                address: 'Shop No. GD 075 Cairns S/C, Cairns, QLD, 4870',
                latitude: -16.925189,
                longitude: 145.771862,
              },
              {
                locationId: '927862',
                address: 'Shop341 Westfield Shopping Cn, West Lakes, SA, 5021',
                latitude: -34.879908,
                longitude: 138.490914,
              },
              {
                locationId: '927863',
                address: 'Shop 1110 Westfield S/C, Oaklands Park, SA, 5046',
                latitude: -35.01591,
                longitude: 138.544396,
              },
              {
                locationId: '927864',
                address: 'Shop 104 Burnside Village, Glenside, SA, 5065',
                latitude: -34.940773,
                longitude: 138.641707,
              },
              {
                locationId: '927865',
                address: 'T72 Westfield Tea Tree Plaza, Modbury, SA, 5092',
                latitude: -34.830622,
                longitude: 138.692134,
              },
              {
                locationId: '927866',
                address: 'Shop 12, Perth, WA, 6000',
                latitude: -31.952095,
                longitude: 115.858216,
              },
              {
                locationId: '927867',
                address: '840 Wellington Street, West Perth, WA, 6005',
                latitude: -31.946802,
                longitude: 115.847578,
              },
              {
                locationId: '927868',
                address: 'SHOP G12 KARRINYUP SHP CTR, KARRINYUP, WA, 6018',
                latitude: -31.876574,
                longitude: 115.77838,
              },
              {
                locationId: '927869',
                address: 'Shop 80B Westfield Whitford, Hillarys, WA, 6025',
                latitude: -31.79667,
                longitude: 115.749201,
              },
              {
                locationId: '927870',
                address: 'Shop256/157 Lakeside Joondalup, Joondalup, WA, 6027',
                latitude: -31.74404,
                longitude: 115.769216,
              },
              {
                locationId: '927871',
                address: 'Tenancy SP129 - 4 Collier Road, Morley, WA, 6062',
                latitude: -31.89614,
                longitude: 115.900289,
              },
              {
                locationId: '927872',
                address: 'Shop SP 5127 Garden City S/C, Booragoon, WA, 6154',
                latitude: -32.033992,
                longitude: 115.835514,
              },
              {
                locationId: '927873',
                address: 'T305 Cockburn Gateway Shopping, Success, WA, 6164',
                latitude: -32.131288,
                longitude: 115.857477,
              },
              {
                locationId: '927874',
                address: 'Shop 57 Rockingham S/C, Rockingham, WA, 6168',
                latitude: -32.289341,
                longitude: 115.747534,
              },
              {
                locationId: '927875',
                address: 'Shop?097?Mandurah?Forum, Mandurah, WA, 6210',
                latitude: -32.535473,
                longitude: 115.742323,
              },
              {
                locationId: '927876',
                address: 'T28/29 Eaton Fair Shopping Ctr, Eaton, WA, 6232',
                latitude: -33.318612,
                longitude: 115.716493,
              },
              {
                locationId: '927877',
                address: 'Shop GF-1 Cat & Fiddle Arcade, Hobart, TAS, 7000',
                latitude: -42.881587,
                longitude: 147.327304,
              },
              {
                locationId: '927878',
                address: '132 Brisbane Street, Launceston, TAS, 7250',
                latitude: -41.437615,
                longitude: 147.13771,
              },
              {
                locationId: '927889',
                address: 'FOREVER NEW - PRAIRIEWOOD',
                latitude: -33.858076,
                longitude: 150.899334,
              },
              {
                locationId: '927890',
                address: 'FOREVER NEW - Adelaide',
                latitude: -34.922181,
                longitude: 138.601263,
              },
              {
                locationId: '927891',
                address: 'Forever New - Perth CBD',
                latitude: -31.952095,
                longitude: 115.858216,
              },
              {
                locationId: '927892',
                address: 'Forever New - Perth CBD',
                latitude: -31.952095,
                longitude: 115.858216,
              },
              {
                locationId: '927893',
                address: 'Forever New - Parramatta',
                latitude: -33.817252,
                longitude: 151.001338,
              },
            ],
            popularScore: 0,
            startDate: '2022-10-05T17:59:54Z',
            endDate: '2025-02-15T01:22:11Z',
            createdAt: '2024-02-15T08:22:11Z',
            updatedAt: '2024-02-15T08:22:11Z',
          },
          {
            id: '919611',
            type: 'INSTORE',
            offerId: '919611',
            title: '6% Cashback on All Purchases',
            description:
              "Forever New is a women's fashion clothing and accessories brand founded in Melbourne, Australia. Emerging in 2006, Forever New is one of the fastest growing Australian brands and is synonymous with quality fashion and a uniquely beautiful style.",
            cashback: '6%',
            categoryCode: 'fashion',
            howItWorks:
              'To receive Cashback on your purchases, shop at participating venues with your card linked to your account. When you’ve finished shopping, you will receive a notification in your app confirming the Cashback amount due. If you have not received a notification within 5 days from the date of your purchase, please let us know. Depending on the retailer’s returns policy, it may take up to 90 days for the Cashback to be settled and deposited in your personal Wallet.\n',
            imageUrl:
              'https://pokitpal-images.s3-ap-southeast-2.amazonaws.com/stage/UploadFiles/CoverShot/advertiser-76a0f34c-80b4-40c6-9bc8-b033051e0fa7.jpg',
            logoUrl:
              'https://pokitpal-images.s3-ap-southeast-2.amazonaws.com/stage/UploadFiles/Logos/advertiser-cf764b91-ff4a-4286-85e1-0f5757be2b19.jpg',
            advertiserName: 'Forever New Instore',
            advertiserAbout:
              "Forever New is a women's fashion clothing and accessories brand founded in Melbourne, Australia. Emerging in 2006, Forever New is one of the fastest growing Australian brands and is synonymous with quality fashion and a uniquely beautiful style.",
            tnc: 'You must complete a transaction using the card linked to your account. Excludes voucher codes, gift cards, cash back and coupon deals.\n',
            website: '',
            phone: '',
            locations: [
              {
                locationId: '927795',
                address: 'SHOP 229A CASUARINA S/C, CASUARINA, NT, 810',
                latitude: -12.374391,
                longitude: 130.881721,
              },
              {
                locationId: '927796',
                address: 'World Square Sydney, Sydney, NSW, 2000',
                latitude: -33.877181,
                longitude: 151.206879,
              },
              {
                locationId: '927797',
                address: 'Tenancy L00.66, Sydney, NSW, 2000',
                latitude: -33.869664,
                longitude: 151.207398,
              },
              {
                locationId: '927798',
                address: 'Shop 2031/2 Westfield Bondi, Bondi Junction, NSW, 2022',
                latitude: -33.892699,
                longitude: 151.250385,
              },
              {
                locationId: '927799',
                address: 'SHOP 141-152, EASTGARDENS, NSW, 2036',
                latitude: -33.944826,
                longitude: 151.224329,
              },
              {
                locationId: '927800',
                address: 'Shop 205 Birkenhead Pt, Drummoyne, NSW, 2047',
                latitude: -33.855523,
                longitude: 151.161854,
              },
            ],
            popularScore: 0,
            startDate: '2022-10-05T17:59:54Z',
            endDate: '2025-02-15T01:22:11Z',
            createdAt: '2024-02-15T08:22:11Z',
            updatedAt: '2024-02-15T08:22:11Z',
          },
          {
            id: '919648',
            type: 'INSTORE',
            offerId: '919648',
            title: '6% Cashback on All Purchases',
            description:
              "Forever New is a women's fashion clothing and accessories brand founded in Melbourne, Australia. Emerging in 2006, Forever New is one of the fastest growing Australian brands and is synonymous with quality fashion and a uniquely beautiful style.",
            cashback: '6%',
            categoryCode: 'fashion',
            howItWorks:
              'To receive Cashback on your purchases, shop at participating venues with your card linked to your account. When you’ve finished shopping, you will receive a notification in your app confirming the Cashback amount due. If you have not received a notification within 5 days from the date of your purchase, please let us know. Depending on the retailer’s returns policy, it may take up to 90 days for the Cashback to be settled and deposited in your personal Wallet.\n',
            imageUrl:
              'https://pokitpal-images.s3-ap-southeast-2.amazonaws.com/stage/UploadFiles/CoverShot/advertiser-0038bd59-3212-4318-a7bc-6353751ed987.jpg',
            logoUrl:
              'https://pokitpal-images.s3-ap-southeast-2.amazonaws.com/stage/UploadFiles/Logos/advertiser-cf764b91-ff4a-4286-85e1-0f5757be2b19.jpg',
            advertiserName: 'Forever New Instore',
            advertiserAbout:
              "Forever New is a women's fashion clothing and accessories brand founded in Melbourne, Australia. Emerging in 2006, Forever New is one of the fastest growing Australian brands and is synonymous with quality fashion and a uniquely beautiful style.",
            tnc: 'You must complete a transaction using the card linked to your account. Excludes voucher codes, gift cards, cash back and coupon deals.\n',
            website: '',
            phone: '',
            locations: [
              {
                locationId: '123',
                latitude: 20.958072,
                longitude: 105.7682692,
                address: 'XQ58+HXJ Đường Phúc La, P. Văn Phú, Phú La, Hà Đông, Hà Nội, Vietnam',
              },
            ],
            popularScore: 0,
            startDate: '2022-10-05T17:59:54Z',
            endDate: '2025-02-15T01:22:11Z',
            createdAt: '2024-02-15T08:22:11Z',
            updatedAt: '2024-02-15T08:22:11Z',
          },
        ],
      },
    },
  },
} as GetInstoreOffersByAdvertiserIdQuery;

export const mockInstoreOffersGroupByAdvertisers = {
  me: {
    cashback: {
      allAdvertisers: {
        edges: [
          {
            node: {
              id: 'A_941956',
              advertiserId: '941956',
              advertiserName: 'Forever New Instore',
              advertiserAbout:
                "Forever New is a women's fashion clothing and accessories brand founded in Melbourne, Australia. Emerging in 2006, Forever New is one of the fastest growing Australian brands and is synonymous with quality fashion and a uniquely beautiful style.",
              type: 'INSTORE',
              offers: [
                {
                  id: '919647',
                  type: 'INSTORE',
                  offerId: '919647',
                  title: '6% Cashback on All Purchases',
                  description:
                    "Forever New is a women's fashion clothing and accessories brand founded in Melbourne, Australia. Emerging in 2006, Forever New is one of the fastest growing Australian brands and is synonymous with quality fashion and a uniquely beautiful style.",
                  cashback: '6%',
                  categoryCode: 'fashion',
                  howItWorks:
                    'To receive Cashback on your purchases, shop at participating venues with your card linked to your account. When you’ve finished shopping, you will receive a notification in your app confirming the Cashback amount due. If you have not received a notification within 5 days from the date of your purchase, please let us know. Depending on the retailer’s returns policy, it may take up to 90 days for the Cashback to be settled and deposited in your personal Wallet.\n',
                  imageUrl:
                    'https://pokitpal-images.s3-ap-southeast-2.amazonaws.com/stage/UploadFiles/CoverShot/advertiser-76a0f34c-80b4-40c6-9bc8-b033051e0fa7.jpg',
                  logoUrl:
                    'https://pokitpal-images.s3-ap-southeast-2.amazonaws.com/stage/UploadFiles/Logos/advertiser-cf764b91-ff4a-4286-85e1-0f5757be2b19.jpg',
                  advertiserName: 'Forever New Instore',
                  advertiserAbout:
                    "Forever New is a women's fashion clothing and accessories brand founded in Melbourne, Australia. Emerging in 2006, Forever New is one of the fastest growing Australian brands and is synonymous with quality fashion and a uniquely beautiful style.",
                  tnc: 'You must complete a transaction using the card linked to your account. Excludes voucher codes, gift cards, cash back and coupon deals.\n',
                  website: '',
                  phone: '',
                  locations: [
                    {
                      locationId: '927795',
                      address: 'SHOP 229A CASUARINA S/C, CASUARINA, NT, 810',
                      latitude: -12.374391,
                      longitude: 130.881721,
                    },
                    {
                      locationId: '927796',
                      address: 'World Square Sydney, Sydney, NSW, 2000',
                      latitude: -33.877181,
                      longitude: 151.206879,
                    },
                    {
                      locationId: '927797',
                      address: 'Tenancy L00.66, Sydney, NSW, 2000',
                      latitude: -33.869664,
                      longitude: 151.207398,
                    },
                    {
                      locationId: '927798',
                      address: 'Shop 2031/2 Westfield Bondi, Bondi Junction, NSW, 2022',
                      latitude: -33.892699,
                      longitude: 151.250385,
                    },
                    {
                      locationId: '927799',
                      address: 'SHOP 141-152, EASTGARDENS, NSW, 2036',
                      latitude: -33.944826,
                      longitude: 151.224329,
                    },
                    {
                      locationId: '927800',
                      address: 'Shop 205 Birkenhead Pt, Drummoyne, NSW, 2047',
                      latitude: -33.855523,
                      longitude: 151.161854,
                    },
                    {
                      locationId: '927801',
                      address: 'Shop 416/7 1 Anderson Street, Chatswood, NSW, 2067',
                      latitude: -33.79735,
                      longitude: 151.183117,
                    },
                    {
                      locationId: '927802',
                      address: 'Shop 1508 Warringah Mall S/C, Brookvale, NSW, 2100',
                      latitude: -33.767587,
                      longitude: 151.266031,
                    },
                    {
                      locationId: '927803',
                      address: 'T3365 Macquarie Shopping Cnt, North Ryde, NSW, 2113',
                      latitude: -33.776719,
                      longitude: 151.120517,
                    },
                    {
                      locationId: '927804',
                      address: 'Shop 226/27,, Burwood, NSW, 2134',
                      latitude: -33.874984,
                      longitude: 151.106278,
                    },
                    {
                      locationId: '927805',
                      address: 'Shop 3089-3091 West Point S/C, BLACKTOWN, NSW, 2148',
                      latitude: -33.77023,
                      longitude: 150.905453,
                    },
                    {
                      locationId: '927806',
                      address: 'Westfield Parramatta, Parramatta, NSW, 2150',
                      latitude: -33.817252,
                      longitude: 151.001338,
                    },
                    {
                      locationId: '927807',
                      address: 'T390 Castle Towers, Castle Hill, NSW, 2154',
                      latitude: -33.730484,
                      longitude: 151.005372,
                    },
                    {
                      locationId: '927808',
                      address: 'SHOP 150 ROUSE HILL TOWN CT, ROUSE HILL, NSW, 2155',
                      latitude: -33.690433,
                      longitude: 150.924072,
                    },
                    {
                      locationId: '927809',
                      address: 'Tenancy 256, 581-583 Polding, WETHERILL PARK, NSW, 2164',
                      latitude: -33.858079,
                      longitude: 150.898283,
                    },
                    {
                      locationId: '927810',
                      address: 'Westfield Liverpool, Liverpool, NSW, 2170',
                      latitude: -33.919004,
                      longitude: 150.924152,
                    },
                    {
                      locationId: '927811',
                      address: 'Shop ML 70 Bankstown Centro, Bankstown, NSW, 2200',
                      latitude: -33.916523,
                      longitude: 151.038488,
                    },
                    {
                      locationId: '927812',
                      address: 'Cnr Cross St and Park Rd, Hurstville, NSW, 2220',
                      latitude: -33.966169,
                      longitude: 151.105196,
                    },
                    {
                      locationId: '927813',
                      address: 'Shop 3027/28/29 - Westfield, Miranda, NSW, 2228',
                      latitude: -34.03496,
                      longitude: 151.100174,
                    },
                    {
                      locationId: '927814',
                      address: 'Shop T217, Erina, NSW, 2250',
                      latitude: -33.437724,
                      longitude: 151.393336,
                    },
                    {
                      locationId: '927815',
                      address: 'Tenancy L01 1023/4, Charlestown, NSW, 2290',
                      latitude: -32.964091,
                      longitude: 151.693623,
                    },
                    {
                      locationId: '927816',
                      address: 'Shop R01001 Crown St Mall, Wollongong, NSW, 2500',
                      latitude: -34.424659,
                      longitude: 150.894195,
                    },
                    {
                      locationId: '927817',
                      address: 'SHOP 227 Lake Entrance Road, Shellharbour, NSW, 2529',
                      latitude: -34.564167,
                      longitude: 150.839137,
                    },
                    {
                      locationId: '927818',
                      address: 'SHOP 067 200 GILCHRIST DRIVE, CAMPBELLTOWN, NSW, 2560',
                      latitude: -34.074829,
                      longitude: 150.797835,
                    },
                    {
                      locationId: '927819',
                      address: 'Tenancy 154, Narellan, NSW, 2567',
                      latitude: -34.042679,
                      longitude: 150.736742,
                    },
                    {
                      locationId: '927820',
                      address: 'Shop EF20, Canberra, ACT, 2601',
                      latitude: -35.2788,
                      longitude: 149.133442,
                    },
                    {
                      locationId: '927821',
                      address: 'Shop T34 Albury Myer Cntrpoint, Albury, NSW, 2640',
                      latitude: -36.080149,
                      longitude: 146.919837,
                    },
                    {
                      locationId: '927822',
                      address: 'Tenancy G.06 Wagga Wagga, Wagga Wagga, NSW, 2650',
                      latitude: -35.115158,
                      longitude: 147.371148,
                    },
                    {
                      locationId: '927823',
                      address: 'Westfield Penrith, Penrith, NSW, 2750',
                      latitude: -33.751489,
                      longitude: 150.693107,
                    },
                    {
                      locationId: '927824',
                      address: 'Shop 161-164 Melbourne Central, Melbourne, VIC, 3000',
                      latitude: -37.811619,
                      longitude: 144.963779,
                    },
                    {
                      locationId: '927825',
                      address: 'Shop T67, Level 1 Spencer St, Melbourne, VIC, 3000',
                      latitude: -37.816009,
                      longitude: 144.952131,
                    },
                    {
                      locationId: '927826',
                      address: 'Tenancy 126, Whiteman St, Southbank, VIC, 3006',
                      latitude: -37.824836,
                      longitude: 144.9583,
                    },
                    {
                      locationId: '927827',
                      address: 'Shop 7South Wharf Retail Tena, Southbank, VIC, 3006',
                      latitude: -37.824961,
                      longitude: 144.950152,
                    },
                    {
                      locationId: '927828',
                      address: 'Tenancy 234 Werribee Plaza, Werribee, VIC, 3030',
                      latitude: -37.876469,
                      longitude: 144.680944,
                    },
                    {
                      locationId: '927829',
                      address: 'T 3550,120-200 Rosamond Rd, Maribyrnong, VIC, 3032',
                      latitude: -37.773686,
                      longitude: 144.888786,
                    },
                    {
                      locationId: '927830',
                      address: 'Tenancy 165A, Watergardens, Taylors Lakes, VIC, 3038',
                      latitude: -37.699299,
                      longitude: 144.775746,
                    },
                    {
                      locationId: '927831',
                      address: 'Shop E00-13, Craigieburn Cntrl, Craigieburn, VIC, 3064',
                      latitude: -37.592899,
                      longitude: 144.913627,
                    },
                    {
                      locationId: '927832',
                      address: 'Tenancy G10 - Northland Shopping, Preston, VIC, 3072',
                      latitude: -37.738523,
                      longitude: 145.03003,
                    },
                    {
                      locationId: '927833',
                      address: 'Shop 206,Cnr Cooper & High St, Epping, VIC, 3076',
                      latitude: -37.6536,
                      longitude: 145.017484,
                    },
                    {
                      locationId: '927834',
                      address: 'L03 Shop 369 Greensborough, Greensborough, VIC, 3088',
                      latitude: -37.702509,
                      longitude: 145.102822,
                    },
                    {
                      locationId: '927835',
                      address: 'Shop T138 Westfield Doncaster, Doncaster, VIC, 3108',
                      latitude: -37.785464,
                      longitude: 145.126216,
                    },
                    {
                      locationId: '927836',
                      address: 'Tenancy 2123 - Eastland Shopping, Ringwood, VIC, 3134',
                      latitude: -37.812682,
                      longitude: 145.22917,
                    },
                    {
                      locationId: '927837',
                      address: 'Tenancy G94 Chadstone, Chadstone, VIC, 3148',
                      latitude: -37.886277,
                      longitude: 145.08295,
                    },
                    {
                      locationId: '927838',
                      address: 'Shop 1077,425 Burwood Highway, Wantirna South, VIC, 3152',
                      latitude: -37.869056,
                      longitude: 145.241375,
                    },
                    {
                      locationId: '927839',
                      address: 'Shop 2087,1239 Nepean Highway, Cheltenham, VIC, 3192',
                      latitude: -37.95887,
                      longitude: 145.055309,
                    },
                    {
                      locationId: '927840',
                      address: 'Shop 120, 28 Beach Street, Frankston, VIC, 3199',
                      latitude: -38.141806,
                      longitude: 145.124071,
                    },
                    {
                      locationId: '927841',
                      address: 'Shop No. 84 Market Square S/C, Geelong, VIC, 3220',
                      latitude: -38.147987,
                      longitude: 144.361684,
                    },
                    {
                      locationId: '927842',
                      address: 'Tenancy 111, Wendouree, VIC, 3355',
                      latitude: -37.534308,
                      longitude: 143.8245,
                    },
                    {
                      locationId: '927843',
                      address: 'Shop 1107/71, Fountain Gate, VIC, 3805',
                      latitude: -38.017395,
                      longitude: 145.304118,
                    },
                    {
                      locationId: '927844',
                      address: 'Tenancy SP108 Cranbourne Park, Cranbourne, VIC, 3977',
                      latitude: -38.109625,
                      longitude: 145.281926,
                    },
                    {
                      locationId: '927845',
                      address: 'Shop 1, The Pavilion, Brisbane, QLD, 4000',
                      latitude: -27.46974,
                      longitude: 153.024918,
                    },
                    {
                      locationId: '927846',
                      address: 'Shop 1-2659 Zone B Level 2,, Chermside, QLD, 4032',
                      latitude: -27.383874,
                      longitude: 153.032517,
                    },
                    {
                      locationId: '927847',
                      address: 'Tenancy 2092 Indooroopilly SC, Indooroopilly, QLD, 4068',
                      latitude: -27.499136,
                      longitude: 152.972682,
                    },
                    {
                      locationId: '927848',
                      address: 'Shop 25 Mt. Ommaney Centre, Mt Ommaney, QLD, 4074',
                      latitude: -27.547926,
                      longitude: 152.939687,
                    },
                    {
                      locationId: '927849',
                      address: 'SHOP 2113 - WESTFIELD, Upper Mt Gravatt, QLD, 4122',
                      latitude: -27.562952,
                      longitude: 153.081055,
                    },
                    {
                      locationId: '927850',
                      address: 'Shop 2210 Westfield Carindale, Carindale, QLD, 4152',
                      latitude: -27.501856,
                      longitude: 153.10196,
                    },
                    {
                      locationId: '927851',
                      address: 'Shop C45A Harbour Town, Biggera Waters, QLD, 4216',
                      latitude: -27.931344,
                      longitude: 153.38808,
                    },
                    {
                      locationId: '927852',
                      address: 'Tenancy 333 Pacific Fair, Broadbeach, QLD, 4218',
                      latitude: -28.03638,
                      longitude: 153.42931,
                    },
                    {
                      locationId: '927853',
                      address: 'Shop 4289, Robina Town Centre, Robina, QLD, 4226',
                      latitude: -28.078175,
                      longitude: 153.384576,
                    },
                    {
                      locationId: '927854',
                      address: 'Tenancy 252, Springfield Lakes, QLD, 4300',
                      latitude: -27.677621,
                      longitude: 152.902152,
                    },
                    {
                      locationId: '927855',
                      address: 'Tenancy 2102/3, Toowoomba, QLD, 4350',
                      latitude: -27.561416,
                      longitude: 151.950418,
                    },
                    {
                      locationId: '927856',
                      address: 'Shop 1232, North Lakes, QLD, 4509',
                      latitude: -27.241076,
                      longitude: 153.016864,
                    },
                    {
                      locationId: '927857',
                      address: 'Shop No. 377B Sunshine Plaza, Maroochydore, QLD, 4558',
                      latitude: -26.65476,
                      longitude: 153.089056,
                    },
                    {
                      locationId: '927858',
                      address: 'SHOP 247/248 STOCKLANDS, ROCKHAMPTON, QLD, 4700',
                      latitude: -29.433221,
                      longitude: 153.340624,
                    },
                    {
                      locationId: '927859',
                      address: 'Caneland Central, Ground Flr, Mackay, QLD, 4740',
                      latitude: -21.138258,
                      longitude: 149.178053,
                    },
                    {
                      locationId: '927860',
                      address: '310 Ross River Rd, Aitkenvale, QLD, 4814',
                      latitude: -19.299238,
                      longitude: 146.763076,
                    },
                    {
                      locationId: '927861',
                      address: 'Shop No. GD 075 Cairns S/C, Cairns, QLD, 4870',
                      latitude: -16.925189,
                      longitude: 145.771862,
                    },
                    {
                      locationId: '927862',
                      address: 'Shop341 Westfield Shopping Cn, West Lakes, SA, 5021',
                      latitude: -34.879908,
                      longitude: 138.490914,
                    },
                    {
                      locationId: '927863',
                      address: 'Shop 1110 Westfield S/C, Oaklands Park, SA, 5046',
                      latitude: -35.01591,
                      longitude: 138.544396,
                    },
                    {
                      locationId: '927864',
                      address: 'Shop 104 Burnside Village, Glenside, SA, 5065',
                      latitude: -34.940773,
                      longitude: 138.641707,
                    },
                    {
                      locationId: '927865',
                      address: 'T72 Westfield Tea Tree Plaza, Modbury, SA, 5092',
                      latitude: -34.830622,
                      longitude: 138.692134,
                    },
                    {
                      locationId: '927866',
                      address: 'Shop 12, Perth, WA, 6000',
                      latitude: -31.952095,
                      longitude: 115.858216,
                    },
                    {
                      locationId: '927867',
                      address: '840 Wellington Street, West Perth, WA, 6005',
                      latitude: -31.946802,
                      longitude: 115.847578,
                    },
                    {
                      locationId: '927868',
                      address: 'SHOP G12 KARRINYUP SHP CTR, KARRINYUP, WA, 6018',
                      latitude: -31.876574,
                      longitude: 115.77838,
                    },
                    {
                      locationId: '927869',
                      address: 'Shop 80B Westfield Whitford, Hillarys, WA, 6025',
                      latitude: -31.79667,
                      longitude: 115.749201,
                    },
                    {
                      locationId: '927870',
                      address: 'Shop256/157 Lakeside Joondalup, Joondalup, WA, 6027',
                      latitude: -31.74404,
                      longitude: 115.769216,
                    },
                    {
                      locationId: '927871',
                      address: 'Tenancy SP129 - 4 Collier Road, Morley, WA, 6062',
                      latitude: -31.89614,
                      longitude: 115.900289,
                    },
                    {
                      locationId: '927872',
                      address: 'Shop SP 5127 Garden City S/C, Booragoon, WA, 6154',
                      latitude: -32.033992,
                      longitude: 115.835514,
                    },
                    {
                      locationId: '927873',
                      address: 'T305 Cockburn Gateway Shopping, Success, WA, 6164',
                      latitude: -32.131288,
                      longitude: 115.857477,
                    },
                    {
                      locationId: '927874',
                      address: 'Shop 57 Rockingham S/C, Rockingham, WA, 6168',
                      latitude: -32.289341,
                      longitude: 115.747534,
                    },
                    {
                      locationId: '927875',
                      address: 'Shop?097?Mandurah?Forum, Mandurah, WA, 6210',
                      latitude: -32.535473,
                      longitude: 115.742323,
                    },
                    {
                      locationId: '927876',
                      address: 'T28/29 Eaton Fair Shopping Ctr, Eaton, WA, 6232',
                      latitude: -33.318612,
                      longitude: 115.716493,
                    },
                    {
                      locationId: '927877',
                      address: 'Shop GF-1 Cat & Fiddle Arcade, Hobart, TAS, 7000',
                      latitude: -42.881587,
                      longitude: 147.327304,
                    },
                    {
                      locationId: '927878',
                      address: '132 Brisbane Street, Launceston, TAS, 7250',
                      latitude: -41.437615,
                      longitude: 147.13771,
                    },
                    {
                      locationId: '927889',
                      address: 'FOREVER NEW - PRAIRIEWOOD',
                      latitude: -33.858076,
                      longitude: 150.899334,
                    },
                    {
                      locationId: '927890',
                      address: 'FOREVER NEW - Adelaide',
                      latitude: -34.922181,
                      longitude: 138.601263,
                    },
                    {
                      locationId: '927891',
                      address: 'Forever New - Perth CBD',
                      latitude: -31.952095,
                      longitude: 115.858216,
                    },
                    {
                      locationId: '927892',
                      address: 'Forever New - Perth CBD',
                      latitude: -31.952095,
                      longitude: 115.858216,
                    },
                    {
                      locationId: '927893',
                      address: 'Forever New - Parramatta',
                      latitude: -33.817252,
                      longitude: 151.001338,
                    },
                  ],
                  popularScore: 0,
                  startDate: '2022-10-05T17:59:54Z',
                  endDate: '2025-02-15T01:22:11Z',
                  createdAt: '2024-02-15T08:22:11Z',
                  updatedAt: '2024-02-15T08:22:11Z',
                },
              ],
            },
          },
          {
            node: {
              id: 'A_941958',
              advertiserId: '941958',
              advertiserName: 'Breadtop',
              advertiserAbout: '',
              type: 'INSTORE',
              offers: [
                {
                  id: '919649',
                  type: 'INSTORE',
                  offerId: '919649',
                  title: '7% Cashback on All Purchases',
                  description:
                    'Breadtop serves more than 100 premium-quality baked goods. All our pastries are baked on-premise at World Square, throughout the day, and are available via self-serve. We offer savoury and sweet bakery items from magnificent cakes, muffins and cupcakes to popular Asian sweets such as moon cakes.\n',
                  cashback: '7%',
                  categoryCode: 'others',
                  howItWorks:
                    'To receive Cashback on your purchases, shop at participating venues with your card linked to your account. When you’ve finished shopping, you will receive a notification in your app confirming the Cashback amount due. If you have not received a notification within 5 days from the date of your purchase, please let us know. Depending on the retailer’s returns policy, it may take up to 90 days for the Cashback to be settled and deposited in your personal Wallet.\n',
                  imageUrl:
                    'https://pokitpal-images.s3-ap-southeast-2.amazonaws.com/stage/UploadFiles/CoverShot/advertiser-0038bd59-3212-4318-a7bc-6353751ed987.jpg',
                  logoUrl:
                    'https://pokitpal-images.s3-ap-southeast-2.amazonaws.com/stage/UploadFiles/Logos/advertiser-bf51d2b0-cb42-4e5d-916e-f747ca03f02b.jpg',
                  advertiserName: 'Breadtop',
                  advertiserAbout: '',
                  tnc: 'You must complete a transaction using the card linked to your account. Excludes voucher codes, gift cards, cash back and coupon deals.\n\n',
                  website: '',
                  phone: '',
                  locations: [
                    {
                      locationId: '928340',
                      address: '40 MAIN ST BOX HILL 3128 AUSTRALIA',
                      latitude: -37.8188708,
                      longitude: 145.1222989,
                    },
                    {
                      locationId: '928341',
                      address: 'SPRINGVALE VIC',
                      latitude: -37.9493465,
                      longitude: 145.1527935,
                    },
                    {
                      locationId: '928342',
                      address: '22 Precision Street Salisbury 4107',
                      latitude: -27.5462866,
                      longitude: 153.029751,
                    },
                    {
                      locationId: '928343',
                      address: '42 Marina Parade Southport QLD 4215',
                      latitude: -27.9686831,
                      longitude: 153.4155735,
                    },
                    {
                      locationId: '928346',
                      address: '87 BARRACK ST, PERTH WA 6000',
                      latitude: -31.9539267,
                      longitude: 115.8604977,
                    },
                    {
                      locationId: '928347',
                      address: 'CARINDALE QLD',
                      latitude: -27.5198367,
                      longitude: 153.1125044,
                    },
                    {
                      locationId: '928348',
                      address: 'SHOP 010, 1341 DANDE, CHADSTONE VIC 3148',
                      latitude: -37.8866874,
                      longitude: 145.081676,
                    },
                    {
                      locationId: '928349',
                      address: 'Upper mount G AU',
                      latitude: -27.5546971,
                      longitude: 153.0799661,
                    },
                    {
                      locationId: '928350',
                      address: 'HOBART AU',
                      latitude: -42.8826055,
                      longitude: 147.3257197,
                    },
                    {
                      locationId: '928351',
                      address: 'HORNSBY NSW',
                      latitude: -33.7046328,
                      longitude: 151.0987055,
                    },
                    {
                      locationId: '928352',
                      address: 'HURSTVILLE',
                      latitude: -33.9645633,
                      longitude: 151.1010187,
                    },
                    {
                      locationId: '928353',
                      address: 'Shop 1051  Knox City Shopping Centre, Wantirna South VIC 3000',
                      latitude: -37.8687349,
                      longitude: 145.2407676,
                    },
                    {
                      locationId: '928354',
                      address: 'OAKLANDS PAR SA',
                      latitude: -35.013249,
                      longitude: 138.5438411,
                    },
                    {
                      locationId: '928355',
                      address: 'Broadbeach AU',
                      latitude: -28.0293438,
                      longitude: 153.4311592,
                    },
                    {
                      locationId: '928356',
                      address: 'KEYSBOROUGH VIC',
                      latitude: -37.9989202,
                      longitude: 145.1743519,
                    },
                    {
                      locationId: '928357',
                      address: 'LOT 22A LVL10. REGENT PL SYDNEY 2000',
                      latitude: -33.8844249,
                      longitude: 151.20268,
                    },
                    {
                      locationId: '928358',
                      address: 'SHOP 27, STRATHFIELD, STRATHFIELD NSW 2135',
                      latitude: -33.8730093,
                      longitude: 151.0931772,
                    },
                    {
                      locationId: '928359',
                      address: 'Sunnybank AU',
                      latitude: -27.5792623,
                      longitude: 153.0627242,
                    },
                    {
                      locationId: '928360',
                      address: 'L-007, THE GLEN SHOP, GLEN WAVERLEY VIC',
                      latitude: -37.8762186,
                      longitude: 145.1652513,
                    },
                    {
                      locationId: '928361',
                      address: 'SYDNEY NSW',
                      latitude: -33.8688197,
                      longitude: 151.2092955,
                    },
                    {
                      locationId: '928362',
                      address: 'SHOP 9 15 WORLD SQUARE, SYDNEY 2000',
                      latitude: -33.8771211,
                      longitude: 151.2069237,
                    },
                    {
                      locationId: '928363',
                      address: 'INDOOROOPIL QLD',
                      latitude: -27.5020067,
                      longitude: 152.9758891,
                    },
                    {
                      locationId: '928364',
                      address: '90 John st, Cabramatta NSW 2166',
                      latitude: -33.8952361,
                      longitude: 150.9349398,
                    },
                    {
                      locationId: '928365',
                      address: '334 VICTORY AVE, CHATSWOOD 2067 Australia',
                      latitude: -33.7927132,
                      longitude: 151.1902539,
                    },
                    {
                      locationId: '928366',
                      address: 'SHOP 1119 WESTFIELD, DONCASTER VIC 3108 Australia',
                      latitude: -37.7868921,
                      longitude: 145.125484,
                    },
                    {
                      locationId: '928367',
                      address: 'SHOP 2559 HIGHPOINT S, MARIBYRNONG VIC 3032',
                      latitude: -37.77322789,
                      longitude: 144.8893046,
                    },
                    {
                      locationId: '928368',
                      address: 'LG 10 580 GEORGE ST, SYDNEY NSW 2000',
                      latitude: -33.8748664,
                      longitude: 151.2069854,
                    },
                    {
                      locationId: '928369',
                      address: 'SHOP Q15 AUBURN CENTRAL, AUBURN 2144 Australia',
                      latitude: -33.8501169,
                      longitude: 151.0317886,
                    },
                    {
                      locationId: '928370',
                      address: '66 Bankstown, City Plaza, Bankstown 2200',
                      latitude: -33.9182478,
                      longitude: 151.0330602,
                    },
                    {
                      locationId: '928371',
                      address: 'SHOP 215 WESTFIELD, BELCONEN 2617 Australia',
                      latitude: -35.2387888,
                      longitude: 149.0667289,
                    },
                    {
                      locationId: '928372',
                      address: 'shop 30 Belmont forum centre, Cloverdale WA 6105',
                      latitude: -31.964962,
                      longitude: 115.9349136,
                    },
                    {
                      locationId: '928373',
                      address: 'SHOP 1-2, GROUND LEV, MELBOURNE VIC 3000',
                      latitude: -37.8100673,
                      longitude: 144.9638486,
                    },
                    {
                      locationId: '928374',
                      address: 'Shop G28, Broadway Centre, Ultimo NSW 2007',
                      latitude: -33.8842201,
                      longitude: 151.1947174,
                    },
                    {
                      locationId: '928375',
                      address: 'Shop 19, Campsie Centre, Campsie 2194',
                      latitude: -33.9130382,
                      longitude: 151.1025158,
                    },
                    {
                      locationId: '928376',
                      address: 'SH 1166/7 W FIELD CAROU, CANNINGTON 6107 Australia',
                      latitude: -32.0194963,
                      longitude: 115.9382998,
                    },
                    {
                      locationId: '928377',
                      address: '109/4-16 Terminus Rd, Castle Hill NSW 2154',
                      latitude: -33.7331603,
                      longitude: 151.006011,
                    },
                    {
                      locationId: '928378',
                      address: 'SH 205 westfield Chermside 4032 Australia',
                      latitude: -27.3829935,
                      longitude: 153.0322839,
                    },
                    {
                      locationId: '928379',
                      address: 'CLAYTON VIC',
                      latitude: -37.9145479,
                      longitude: 145.127492,
                    },
                    {
                      locationId: '928380',
                      address: 'SHOP 18 COLBURNGATEE, SUCCESS WA 6164',
                      latitude: -32.1309688,
                      longitude: 115.8572868,
                    },
                    {
                      locationId: '928381',
                      address: 'MELBOURNE VIC',
                      latitude: -37.8136276,
                      longitude: 144.9630576,
                    },
                    {
                      locationId: '928382',
                      address: '243 253 WALTER RD W, MORLEY 6062 Australia',
                      latitude: -31.8944564,
                      longitude: 115.8956801,
                    },
                    {
                      locationId: '928383',
                      address: 'SHOP 171 152 BUNNERON R, EASTGARDENS 2036 Australia',
                      latitude: -33.9447964,
                      longitude: 151.2231422,
                    },
                    {
                      locationId: '928384',
                      address: 'EASTLANDN SHOPPING CENTRE, RINGWOOD 3134 Australia',
                      latitude: -37.8126592,
                      longitude: 145.2292803,
                    },
                    {
                      locationId: '928385',
                      address: 'GROUND FLOOR, 55 ELI, MELBOURNE VIC 3000',
                      latitude: -37.8136216,
                      longitude: 144.9630765,
                    },
                    {
                      locationId: '928386',
                      address: 'SHOP T126 FOREST HILL, FOREST HILL VIC 3131',
                      latitude: -37.8354108,
                      longitude: 145.1646721,
                    },
                    {
                      locationId: '928387',
                      address: 'SHOP 01 815-825, GEO, SYDNEY NSW 2000',
                      latitude: -33.8828704,
                      longitude: 151.2034376,
                    },
                    {
                      locationId: '928388',
                      address: 'Harbourtown shopping CE Biggera water 4216 Australia',
                      latitude: -27.9300179,
                      longitude: 153.3870655,
                    },
                    {
                      locationId: '928389',
                      address: 'SHOP G005, LIDCOMBE 2141 Australia',
                      latitude: -33.8494164,
                      longitude: 151.0488042,
                    },
                    {
                      locationId: '928390',
                      address: '57B BURNS RD, WAHROONGA NSW 2076',
                      latitude: -33.7153386,
                      longitude: 151.1263519,
                    },
                    {
                      locationId: '928391',
                      address: 'B 91 Queen Street Brisbane 4000 Australia',
                      latitude: -27.4706058,
                      longitude: 153.0248758,
                    },
                    {
                      locationId: '928392',
                      address: '429 High ST, Preston VIC 3072',
                      latitude: -37.7392949,
                      longitude: 145.0034197,
                    },
                    {
                      locationId: '928393',
                      address: 'Shop 32, 1 rider Blvd Rhodes 2138',
                      latitude: -33.8325315,
                      longitude: 151.0861678,
                    },
                    {
                      locationId: '928394',
                      address: 'SHOP 1118, CHELTENHAM VIC 3192',
                      latitude: -37.9673551,
                      longitude: 145.0569545,
                    },
                    {
                      locationId: '928395',
                      address: '27 ALFRIEDR ST, ST ALBANS VIC 3021',
                      latitude: -37.743197,
                      longitude: 144.800438,
                    },
                    {
                      locationId: '928396',
                      address: 'Shop 4013 Top Ryde City, Ryde 2112 Australia',
                      latitude: -33.8118097,
                      longitude: 151.1064854,
                    },
                    {
                      locationId: '928397',
                      address: 'SHOP 1005, WESTPOINT, BLACKTOWN NSW 2148',
                      latitude: -33.7702867,
                      longitude: 150.9059341,
                    },
                    {
                      locationId: '928659',
                      address: 'Shop 1051, Westfield Knox City, 425 Burwood Hwy, Wantirna South, VIC 3152',
                      latitude: -37.8687349,
                      longitude: 145.2407676,
                    },
                    {
                      locationId: '928660',
                      address: 'Shop L-007, The Glen Shopping Centre, 235 Springvale Road, Glen Waverley, VIC 3150',
                      latitude: -37.8763119,
                      longitude: 145.165212,
                    },
                    {
                      locationId: '928661',
                      address: 'Shop K0115, Indooroopilly Shopping Centre, 322 Moggill Rd, Indooroopilly, QLD 4068',
                      latitude: -27.5001761,
                      longitude: 152.9721547,
                    },
                  ],
                  popularScore: 0,
                  startDate: '2022-10-05T18:00:21Z',
                  endDate: '2025-02-15T01:22:11Z',
                  createdAt: '2024-02-15T08:22:11Z',
                  updatedAt: '2024-02-15T08:22:11Z',
                },
              ],
            },
          },
        ],
        pageInfo: {
          hasNextPage: false,
          endCursor: 'WzEzLjA5MDgxNzIzMjc3NTk5NF0=',
          totalCount: 1,
          totalPages: 1,
        },
      },
    },
  },
} as GetCashbackOffersGroupByAdvertiserQuery;

export const mockCashbackLinkedCards: CashbackLinkedCardsQuery = {
  me: {
    cashback: {
      linkedCards: {
        cards: [
          {
            id: 1,
            description: 'xxx',
            cardMasked: '1111-2222-3333-5555',
            issuer: 'visa',
            isExpired: false,
            expiry: '2023-10-01T00:00:00',
            lastFour: '5555',
            provider: 'Employment Hero',
          },
          {
            id: 2,
            description: 'xxx',
            cardMasked: '1111-2222-3333-4444',
            issuer: 'mastercard',
            isExpired: false,
            expiry: '2024-10-01T01:10:00',
            lastFour: '4444',
            provider: 'NAB',
          },
          {
            id: 3,
            description: 'xxx',
            cardMasked: '1111-2222-3333-9999',
            issuer: 'visa',
            isExpired: false,
            expiry: '2025-10-01T02:20:00',
            lastFour: '9999',
            provider: 'Westpac',
          },
          {
            id: 4,
            description: 'xxx',
            cardMasked: '1111-2222-3333-4444',
            issuer: 'mastercard',
            isExpired: false,
            expiry: '2024-01-01T01:10:00',
            lastFour: '784',
            provider: 'Citibank',
          },
          {
            id: 5,
            description: 'xxx',
            cardMasked: '1111-2222-3333-9999',
            issuer: 'visa',
            isExpired: false,
            expiry: '2025-10-01T02:20:00',
            lastFour: '2552',
            provider: 'Westpac',
          },
          {
            id: 6,
            description: 'xxx',
            cardMasked: '1111-2222-3333-4444',
            issuer: 'mastercard',
            isExpired: false,
            expiry: '2024-10-01T01:10:00',
            lastFour: '5454',
            provider: 'NAB',
          },
          {
            id: 7,
            description: 'xxx',
            cardMasked: '1111-2222-3333-9999',
            issuer: 'visa',
            isExpired: false,
            expiry: '2025-10-01T02:20:00',
            lastFour: '1114',
            provider: 'Westpac',
          },
          {
            id: 8,
            description: 'xxx',
            cardMasked: '1111-2222-3333-4444',
            issuer: 'mastercard',
            isExpired: false,
            expiry: '2024-10-01T01:10:00',
            lastFour: '5859',
            provider: 'NAB',
          },
          {
            id: 9,
            description: 'xxx',
            cardMasked: '1111-2222-3333-9999',
            issuer: 'visa',
            isExpired: false,
            expiry: '2025-10-01T02:20:00',
            lastFour: '6426',
            provider: 'Westpac',
          },
          {
            id: 10,
            description: 'xxx',
            cardMasked: '1111-2222-3333-4444',
            issuer: 'mastercard',
            isExpired: false,
            expiry: '2024-10-01T01:10:00',
            lastFour: '8742',
            provider: 'NAB',
          },
        ],
      },
    },
  },
};
