const BENEFITS_HELP_CENTRE_LINK = 'https://help.swagapp.com/hc/categories/6186480541839';
const MONEY_HELP_CENTRE_LINK = 'https://help.swagapp.com/hc/categories/6044879701135';
const SUPPORT_FAQ_LINK =
  'https://employmenthero.zendesk.com/hc/en-au/articles/5623820636431-FAQ-What-do-I-need-to-know-as-an-employee-using-the-Employment-Hero-app';

const BENEFITS_CASHBACK_FAQ_LINK = 'https://help.swagapp.com/hc/en-au/articles/6095712466063-Cashback-FAQ-Benefits';

const MONEY_FAQ_LINK = 'https://help.swagapp.com/hc/en-au/articles/6052605941647-Swag-Spend-Account-FAQ-Money';

const FINANCIAL_WELLNESS_AT_WORK_LINK = 'https://swagapp.com/blog/financial-wellness-at-work/';
const NEW_FINANCIAL_WELLNESS_AT_WORK_LINK = 'https://employmenthero.com/blog/financial-wellness-at-work/';
const FINANCIAL_WELLNESS_BULLETPROOF_BUDGET_LINK = 'https://swagapp.com/blog/how-to-create-a-bulletproof-budget/';
const NEW_FINANCIAL_WELLNESS_BULLETPROOF_BUDGET_LINK =
  'https://employmenthero.com/blog/how-to-create-bulletproof-budget/';
const FINANCIAL_WELLNESS_CUT_EVERYDAY_EXPENSES_LINK = 'https://swagapp.com/blog/how-to-cut-everyday-expenses/';
const NEW_FINANCIAL_WELLNESS_CUT_EVERYDAY_EXPENSES_LINK = 'https://employmenthero.com/blog/cutting-costs/';
const FINANCIAL_WELLNESS_EMPLOYEE_BENEFITS_LINK = 'https://swagapp.com/blog/top-employee-benefits-in-2024/';
const NEW_FINANCIAL_WELLNESS_EMPLOYEE_BENEFITS_LINK = 'https://employmenthero.com/blog/top-employee-benefits-in-2024/';

// For AU
const FINANCIAL_WELLNESS_MONEYSMART_LINK_AU = 'https://moneysmart.gov.au/';
const FINANCIAL_WELLNESS_NATIONAL_DEBT_HELPLINE_LINK_AU = 'https://ndh.org.au/';
const FINANCIAL_WELLNESS_SMALL_BUSINESS_DEBT_HELPLINE_LINK_AU = 'https://sbdh.org.au/';

// For UK
const FINANCIAL_WELLNESS_MONEY_HELPER_LINK_UK = 'https://www.moneyhelper.org.uk/en';
const FINANCIAL_WELLNESS_CITIZEN_ADVICE_LINK_UK = 'https://www.citizensadvice.org.uk/';
const FINANCIAL_WELLNESS_NATIONAL_DEBT_HELPLINE_LINK_UK = 'https://nationaldebtline.org/';

type FinancialWellnessLink =
  | typeof FINANCIAL_WELLNESS_AT_WORK_LINK
  | typeof NEW_FINANCIAL_WELLNESS_AT_WORK_LINK
  | typeof FINANCIAL_WELLNESS_BULLETPROOF_BUDGET_LINK
  | typeof NEW_FINANCIAL_WELLNESS_BULLETPROOF_BUDGET_LINK
  | typeof FINANCIAL_WELLNESS_CUT_EVERYDAY_EXPENSES_LINK
  | typeof NEW_FINANCIAL_WELLNESS_CUT_EVERYDAY_EXPENSES_LINK
  | typeof FINANCIAL_WELLNESS_EMPLOYEE_BENEFITS_LINK
  | typeof NEW_FINANCIAL_WELLNESS_EMPLOYEE_BENEFITS_LINK
  | typeof FINANCIAL_WELLNESS_MONEYSMART_LINK_AU
  | typeof FINANCIAL_WELLNESS_NATIONAL_DEBT_HELPLINE_LINK_AU
  | typeof FINANCIAL_WELLNESS_SMALL_BUSINESS_DEBT_HELPLINE_LINK_AU
  | typeof FINANCIAL_WELLNESS_MONEY_HELPER_LINK_UK
  | typeof FINANCIAL_WELLNESS_CITIZEN_ADVICE_LINK_UK
  | typeof FINANCIAL_WELLNESS_NATIONAL_DEBT_HELPLINE_LINK_UK;

export {
  BENEFITS_HELP_CENTRE_LINK,
  MONEY_HELP_CENTRE_LINK,
  SUPPORT_FAQ_LINK,
  BENEFITS_CASHBACK_FAQ_LINK,
  MONEY_FAQ_LINK,
  FINANCIAL_WELLNESS_AT_WORK_LINK,
  NEW_FINANCIAL_WELLNESS_AT_WORK_LINK,
  FINANCIAL_WELLNESS_BULLETPROOF_BUDGET_LINK,
  NEW_FINANCIAL_WELLNESS_BULLETPROOF_BUDGET_LINK,
  FINANCIAL_WELLNESS_CUT_EVERYDAY_EXPENSES_LINK,
  NEW_FINANCIAL_WELLNESS_CUT_EVERYDAY_EXPENSES_LINK,
  FINANCIAL_WELLNESS_EMPLOYEE_BENEFITS_LINK,
  NEW_FINANCIAL_WELLNESS_EMPLOYEE_BENEFITS_LINK,
  FINANCIAL_WELLNESS_MONEYSMART_LINK_AU,
  FINANCIAL_WELLNESS_NATIONAL_DEBT_HELPLINE_LINK_AU,
  FINANCIAL_WELLNESS_SMALL_BUSINESS_DEBT_HELPLINE_LINK_AU,
  FINANCIAL_WELLNESS_MONEY_HELPER_LINK_UK,
  FINANCIAL_WELLNESS_CITIZEN_ADVICE_LINK_UK,
  FINANCIAL_WELLNESS_NATIONAL_DEBT_HELPLINE_LINK_UK,
  type FinancialWellnessLink,
};
