export enum AutoEnrolStatus {
  NO_SWAG_CARD = 'NO_SWAG_CARD',
  INTERNAL_SERVER = 'INTERNAL_SERVER',
  CAN_NOT_ENROL_SWAG_CARD = 'CAN_NOT_ENROL_SWAG_CARD',
  NO_OEM_DATA = 'NO_OEM_DATA',
  NO_POKITPAL_TOKEN = 'NO_POKITPAL_TOKEN',

  MCD_ERROR = 'MCD_ERROR',
  ENROLLED = 'ENROLLED',
  RE_ENROLLED_TO_NEW_SWAG_CARD = 'RE_ENROLLED_TO_NEW_SWAG_CARD',
  BANK_UPDATED = 'BANK_UPDATED',
  MISSING_WALLET_DETAIL = 'MISSING_WALLET_DETAIL',
}

export const EMPLOYMENT_HERO_PROVIDER = 'Employment Hero';

export const MAXIMUM_OTHER_CARDS_TO_ADD = 9;
