import type { CashbackTermsAndConditionsItem } from '../../../../../new-graphql/generated';

export const termsAndConditionsContent: CashbackTermsAndConditionsItem[] = [
  {
    text: 'Employment Hero Rewards - Terms of Use',
    textVariant: 'small-bold',
    type: 'text',
  },
  {
    text: 'Employment Hero Financial Services Pty Ltd ABN: 58 606 879 663 ("Employment Hero", "we", "us" and "our) welcomes you to Employment Hero Rewards program that we have launched to help our users ("User", "you" and "your) earn rewards on their everyday purchases through partner merchants ("Merchants"). These rewards may comprise cash rebates, vouchers for discounts, free entry or other special benefits or rights ("Rewards)',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: 'These Terms of Use ("Terms") govern your access to and use of Employment Hero Rewards and any services or features that we make available from time to time relating to Employment Hero Rewards. ',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: '1. YOUR ACCEPTANCE OF THESE TERMS',
    textVariant: 'small-bold',
    type: 'text',
  },
  {
    text: 'By accessing or using the Employment Hero Rewards you agree to these Terms, you agree to be bound by these Terms. We will collect and use your information in accordance with our',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: 'Privacy Policy.',
    textVariant: 'small',
    type: 'link',
    url: 'https://employmenthero.com/legals/privacy-policy/',
  },
  {
    text: 'If you do not agree to all the terms and conditions of these Terms, you should not access or use Employment Hero Rewards.',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: '2. USE OF EMPLOYMENT HERO REWARDS',
    textVariant: 'small-bold',
    type: 'text',
  },
  {
    text: 'In order to access and use Employment Hero Rewards, you must hold an account ("Account") and be a user of the EH Platform and must agree to the',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: 'General Terms',
    textVariant: 'small',
    type: 'link',
    url: 'https://employmenthero.com/legals/terms-conditions/hr-product/',
  },
  {
    text: 'General Terms of the EH Platform ("General Terms"). You are required to provide and confirm all information requested by us in order to provide access to Employment Hero Rewards. This information includes but is not limited to your name, phone number, email address, and payment account information ("User Information"). You must notify us of any changes to your User Information.',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: 'We may determine at our complete discretion the eligibility of your access to Employment Hero Rewards.',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: '3. LINKING YOUR PAYMENT CARD',
    textVariant: 'small-bold',
    type: 'text',
  },
  {
    text: `In order to access and use Employment Hero Rewards and to start receiving Rewards from us for qualifying purchases of the Merchant's goods or services, you must link at least one eligible Australian issued debit or credit card (a "Payment Card") to your Account. A Payment Card must be in the same name as your Account. It is possible to link up to X Payment Cards in your Account. We will let you know if the card you are attempting to link is not eligible for use with Employment Hero Rewards. All determinations as to whether a card is eligible to be a Payment Card are at our sole discretion. Certain types of cards are not eligible to be a Payment Card, these include prepaid cards, corporate cards, purchasing cards, gift cards and government-administered prepaid cards.`,
    textVariant: 'small',
    type: 'text',
  },
  {
    text: '4. USE OF ENROLLED CARDS AND TRANSACTION INFORMATION',
    textVariant: 'small-bold',
    type: 'text',
  },
  {
    text: 'By registering a Payment Card, you authorise us to share your payment card information with the third-parties that enable us to offer Employment Hero Rewards including to payment scheme providers such as Visa and MasterCard (“Third-Party Service Providers”). You authorise the Third-Party Service Providers to monitor transactions on your registered Payment Card(s) to identify qualifying purchases in order to determine whether you have qualified for or earned Rewards, and for the Third-Party Service Providers to share such transaction details with us to enable and offer Employment Hero Rewards and other related services. You agree that Employment Hero and other Third-Party Service Providers may view your transactions made by you with Merchants. You may opt-out of transaction monitoring on the Payment Card(s) you have registered through your Account.',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: 'For additional information about how we use and share your information, please read our ',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: 'Privacy Policy.',
    textVariant: 'small',
    type: 'link',
    url: 'https://employmenthero.com/legals/privacy-policy/',
  },
  {
    text: '5. REWARDS',
    textVariant: 'small-bold',
    type: 'text',
  },
  {
    text: 'Subject to these Terms, we will automatically provide Rewards to you when you make an eligible purchase with your Payment Card or perform other qualifying actions identified by us from time to time. Employment Hero will act as your agent to collect any cash rebate payable by a Merchant when you make an eligible purchase using the Payment Card.',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: 'Once we receive the Reward from the Merchant, we will update your Account to reflect the amount of the Reward that we have received and which we hold on your behalf. We only make Rewards available in your Account once we have received the Rewards from the Merchant. Rewards that you are entitled to receive as a result of a qualifying purchase at a local merchant will generally be reflected in your Account within 7 business days of purchase. Depending on the qualifying purchase we may not make the Rewards immediately available in your Account and the Rewards may not be available in your Account until such time as any return periods imposed by the Merchant have concluded.',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: 'Not all qualifying purchases made with your Payment Card may be eligible for Rewards and this includes where other promotions apply. For example, we may be unable to obtain certain transactions made with your Payment Card where: ',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: 'purchases require you to enter your Personal Identification Number (“PIN”) for your Payment Card; ',
    textVariant: 'small',
    type: 'text',
    showListItemSymbol: true,
  },
  {
    text: 'purchases you initiate through identification technology that substitutes for a PIN;',
    textVariant: 'small',
    type: 'text',
    showListItemSymbol: true,
  },
  {
    text: 'payments made through other payment methods (such as a digital wallet or a third-party payment application, where you may choose your Payment Card as a funding source but you do not present your Payment Card directly to the merchant); or',
    textVariant: 'small',
    type: 'text',
    showListItemSymbol: true,
  },
  {
    text: 'payments of existing balances, balance transfers',
    textVariant: 'small',
    type: 'text',
    showListItemSymbol: true,
  },
  {
    text: 'Where purchases are made online, we may require you to have cookies enabled until the payment is complete.',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: '9. ERRORS',
    textVariant: 'small-bold',
    type: 'text',
  },
  {
    text: 'Without limiting these Terms, where any Rewards are provided to you in error, we reserve the right to debit the erroneous Rewards from your Account. If you believe that your Account does not accurately reflect your Rewards, please contact us. ',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: 'You must notify us of any errors within 15 days of such information being made available to you. If you do not notify us of any such errors within such 15 days, you will forfeit the right to contest a transaction, except to the extent such forfeiture is prohibited by applicable law.',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: '7. RETURNS',
    textVariant: 'small-bold',
    type: 'text',
  },
  {
    text: 'Without limiting these Terms, if you return, chargeback, cancel, dispute, or otherwise request a refund for an eligible purchase for which you have already received Rewards, we will reduce the balance of the Rewards in your Account by the amount of Rewards you received for such transaction. If the balance of Rewards in your Account is less than the amount of Rewards you received for such transaction, we will offset the applicable amount of Rewards from any Rewards you would otherwise receive for future qualifying actions.',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: '8. REDEEMING REWARDS',
    textVariant: 'small-bold',
    type: 'text',
  },
  {
    text: 'Subject to these Terms and our approval, you may request that we redeem Rewards from your Account. In order to redeem the Rewards, the minimum balance of your Rewards must be equivalent to at least $30. We will generally redeem the Rewards from your    Account and credit your designated Australian bank account, PayPal account, or other payment method permitted by us and designated by you (“Redemption Method”) within 5 business days of when we receive your redemption request. ',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: 'By redeeming Rewards from your Account, you authorise us to electronically credit your Redemption Method for the applicable redemption amount. This authorisation will remain in full force and effect until you cease using Employment Hero Rewards, disable it from your Account or until you otherwise notify us. ',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: 'if you make a change in your Redemption Method, this will take effect within 3 business days of receiving the notice of change. Any redemption that has already been processed prior to the change in Redemption Method being approved cannot be changed, and we have no responsibility for a failure for any funds to be delivered. You are solely responsible for verifying the accuracy and completeness of any credits to your Redemption Method performed by us. If the redeemed Rewards are unable to be processed and the funds are returned to us, we are not responsible for any loss you suffer',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: 'Certain limits may apply to the redemption of any Rewards. You may only redeem Rewards up to the equivalent of $250 in any day. Without limiting any of the other conditions of these Terms, we may modify the redemption terms for the Rewards at any time in our sole discretion.',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: '9. FEES',
    textVariant: 'small-bold',
    type: 'text',
  },
  {
    text: 'We do not charge you any fees for accessing or using Employment Hero Rewards. Employment Hero Rewards is offered as part of the EH Platform and is free for use by a User. ',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: '10. TAXES',
    textVariant: 'small-bold',
    type: 'text',
  },
  {
    text: 'All amounts paid to you under these Terms are exclusive of any applicable withholding, sales, use, excise, value added, or other taxes',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: 'You acknowledge and agree that you are solely responsible and liable for determining, paying, withholding, filing, and reporting all taxes, duties, and other governmental assessments associated with your activity in connection with Employment Hero Rewards. ',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: 'You agree to promptly and fully reimburse and indemnify us for any taxes, penalties, and interest assessed by any taxing authority regarding amounts owed by you in connection with these Terms.',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: '11. GENERAL TERMS',
    textVariant: 'small-bold',
    type: 'text',
  },
  {
    text: 'Employment Hero Rewards may only be accessed and used for your own personal, non-commercial use and not on behalf of or for the benefit of any third party.',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: 'You acknowledge and agree that the Rewards: ',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: 'Are redeemed solely by the Employment Hero and are not underwritten, funded, sponsored, or otherwise provided by any third party, including, but not limited to any Third-Party Service Provider or Merchants;',
    textVariant: 'small',
    type: 'text',
    showListItemSymbol: true,
  },
  {
    text: 'Have no cash or other monetary value and do not act as a substitute for real currency until redeemed; and ',
    textVariant: 'small',
    type: 'text',
    showListItemSymbol: true,
  },
  {
    text: 'You further acknowledge and agree that:',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: 'Employment Hero, in its sole discretion, may impose limits, terms, and conditions on the Rewards, including, but not limited to, limits on the amount of Rewards that may be received and redeemed, and may adjust the Rewards balance in your Account;',
    textVariant: 'small',
    type: 'text',
    showListItemSymbol: true,
  },
  {
    text: 'Employment Hero is not a party to your Payment Card transactions; and',
    textVariant: 'small',
    type: 'text',
    showListItemSymbol: true,
  },
  {
    text: 'Employment Hero is not responsible, and has no liability for, any products or services that are paid for with your Payment Card. You must resolve all disputes related to any products or services that are paid for with your Payment Card directly with the Merchant or the financial institution that issued your Payment Card.',
    textVariant: 'small',
    type: 'text',
    showListItemSymbol: true,
  },
  {
    text: 'The Rewards cannot be transferred or sent to any other User or third party.In accessing or using Employment Hero Rewards or your Account, you must not:',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: 'Knowingly or recklessly provide us with false, inaccurate or incomplete information;',
    textVariant: 'small',
    type: 'text',
    showListItemSymbol: true,
  },
  {
    text: 'Use the service for the purpose of obtaining, processing, distributing, viewing, assessing, analysing, copying or replicating any information, methods or processes related to Employment Hero Rewards (including without limitation by way of data scraping, the use of collection or accumulation tools and robotic or scripted responses);',
    textVariant: 'small',
    type: 'text',
    showListItemSymbol: true,
  },
  {
    text: "Reverse engineer, disassemble or otherwise attempt to construct, copy or replicate Employment Hero Rewards' source code, formulas or processes;",
    textVariant: 'small',
    type: 'text',
    showListItemSymbol: true,
  },
  {
    text: 'Interfere with the security of the Account or Employment Hero Rewards or the secure and safe use of the Account or Employment Hero Rewards by any other User;',
    textVariant: 'small',
    type: 'text',
    showListItemSymbol: true,
  },
  {
    text: 'Use the Account or Employment Hero Rewards for any purpose that is unlawful or prohibited or in a way which infringes the intellectual property rights or other rights of any person (including us);',
    textVariant: 'small',
    type: 'text',
    showListItemSymbol: true,
  },
  {
    text: 'Knowingly or recklessly use or take advantage of a process, technical or technological error, loophole or glitch in Employment Hero Rewards;',
    textVariant: 'small',
    type: 'text',
    showListItemSymbol: true,
  },
  {
    text: 'Access or use Employment Hero Rewards in a way that may infringe upon the intellectual property or other rights of any third party, including, without limitation, trademark, copyright, privacy, or publicity rights',
    textVariant: 'small',
    type: 'text',
    showListItemSymbol: true,
  },
  {
    text: 'Use systematic, repetitive or other related methods which are designed to generate or obtain repetitive and repeated amounts of data or other information from or to Employment Hero Rewards or which may otherwise place an unreasonable load on the infrastructure of Employment Hero Rewards; or',
    textVariant: 'small',
    type: 'text',
    showListItemSymbol: true,
  },
  {
    text: 'Do anything else which may interfere with or negatively affect the operation of Employment Hero Rewards.',
    textVariant: 'small',
    type: 'text',
    showListItemSymbol: true,
  },
  {
    text: 'For our compliance purposes and in order to provide Employment Hero Rewards to you, you hereby authorise us to, directly or through a third party, obtain, verify, and record information and documentation for purposes of verifying your identity and your Payment Card and Redemption Account information.',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: '12. THIRD PARTY TRAVEL SERVICES',
    textVariant: 'small-bold',
    type: 'text',
  },
  {
    text: 'You may be able to earn Rewards on Employment Hero Rewards when you purchase through third-party travel services, such as hotel reservations and car rental services (the “Travel Services”), from third-party suppliers (“Third-Party Suppliers”). Separate terms and conditions may apply to the Travel Services.',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: 'You should read these terms and conditions carefully before purchasing any Travel Services. By purchasing Travel Services through the Services, you agree to be bound by the terms and conditions of the Travel Services established and provided by the Third-Party Supplier,',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: 'We will provide you with Rewards relating to Travel Services within 90 days of the Travel Services being provided.',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: '13. OWNERSHIP AND PROPRIETARY RIGHTS IN THE SERVICES',
    textVariant: 'small-bold',
    type: 'text',
  },
  {
    text: 'All right, title, and interest in and to Employment Hero Rewards, including any updates, upgrades, and modifications, information, data, graphics and any associated patents, trademarks, copyrights, trade secrets, and other intellectual property rights, belong solely and exclusively to Employment Hero and its licensors, and unless expressly provided in these Terms, we do not grant you any licenses or other rights, express or implied, in relation to Employment Hero Rewards.',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: 'Subject to these Terms, we grant you a limited, revocable, personal, non-exclusive, and non-transferable right and license to access and use Employment Hero Rewards and your Account for personal purposes. ',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: '14. PAYMENT TERMS',
    textVariant: 'small-bold',
    type: 'text',
  },
  {
    text: 'By providing your payment account information, including Payment Card and Redemption Method information, to us, you acknowledge and agree that: ',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: 'you are authorised to provide such information to us; ',
    textVariant: 'small',
    type: 'text',
    showListItemSymbol: true,
  },
  {
    text: 'you are legally authorised to perform payments from the Payment Card, and accept payments through the Redemption Method; and',
    textVariant: 'small',
    type: 'text',
    showListItemSymbol: true,
  },
  {
    text: 'such action does not violate the terms and conditions applicable to your use of such Payment Card or Redemption Method or any applicable law. ',
    textVariant: 'small',
    type: 'text',
    showListItemSymbol: true,
  },
  {
    text: 'When you authorise a payment through Employment Hero Reward, you warrant that there are sufficient funds to complete the payment.',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: '15. THIRD-PARTY CONTENT',
    textVariant: 'small-bold',
    type: 'text',
  },
  {
    text: 'The information presented by third-parties through Employment Hero Rewards is made available solely for general information purposes. We do not warrant the accuracy, completeness, or usefulness of this information. ',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: 'Any reliance you place on such information is strictly at your own risk. You release and hold us harmless for all liability and responsibility arising from any reliance placed on such materials by you, unless we are responsible at law. ',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: '16. SUSPENSION AND TERMINATION',
    textVariant: 'small-bold',
    type: 'text',
  },
  {
    text: 'We may, in our sole discretion, suspend, limit, or terminate your Account  or your access to and use of Employment Hero Rewards, including any Rewards in your Account, with written notice to you, including, but not limited to, if we suspect that your access to or use of Employment Hero Rewards or your Account violates these Terms or any applicable law. We may exercise any rights we have to recover any funds from you which are afforded to us under these Terms or at law.',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: 'You can cease using Employment Hero Rewards at any time. You may disable Employment Hero Rewards from your Account',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: '17. INDEMNIFICATION',
    textVariant: 'small-bold',
    type: 'text',
  },
  {
    text: 'To the maximum extent permitted by law, you agree to indemnify, hold harmless, and release us, our associated entities, directors, officer, employees, service providers and agents, as well as any scheme provider, from and against all claims, demands, actions, suits, proceedings, damages, costs, lawsuits, fines, losses, penalties, liabilities, and expenses, including reasonable legal fees awarded by a court, that arise out of or relate to:',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: 'your conduct and use of Employment Hero Rewards;',
    textVariant: 'small',
    type: 'text',
    showListItemSymbol: true,
  },
  {
    text: 'your breach of these Terms, our General Terms or our Privacy Policy;',
    textVariant: 'small',
    type: 'text',
    showListItemSymbol: true,
  },
  {
    text: 'your breach of any law, regulation or rule;',
    textVariant: 'small',
    type: 'text',
    showListItemSymbol: true,
  },
  {
    text: 'your violation or breach of any copyright, intellectual property, trade secrets, patents, trademarks, service marks or any other proprietary right we have under law;',
    textVariant: 'small',
    type: 'text',
    showListItemSymbol: true,
  },
  {
    text: 'your failure to secure or keep secret your Account password;',
    textVariant: 'small',
    type: 'text',
    showListItemSymbol: true,
  },
  {
    text: 'any information that you provide to us;',
    textVariant: 'small',
    type: 'text',
    showListItemSymbol: true,
  },
  {
    text: 'any damage that you may cause to platform or services (including Employment Hero Rewards) or to any other User; or',
    textVariant: 'small',
    type: 'text',
    showListItemSymbol: true,
  },
  {
    text: 'any right exercised by us under these Terms.',
    textVariant: 'small',
    type: 'text',
    showListItemSymbol: true,
  },
  {
    text: 'This indemnity includes, without limitation, liability relating to intellectual property rights, defamation and breaches of privacy.',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: 'This indemnity does not limit any other indemnity provided under the',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: 'General Terms.',
    textVariant: 'small',
    type: 'link',
    url: 'https://employmenthero.com/legals/terms-conditions/hr-product/',
  },
  {
    text: '18. LIMITATIONS OF LIABILITY',
    textVariant: 'small-bold',
    type: 'text',
  },
  {
    text: 'Except for liability that cannot be excluded or limited by law, each party excludes liability for any indirect or consequential losses, including but not limited to loss of profits or revenue, loss of goodwill, damage to reputation, loss of anticipated savings, loss or corruption of data, loss, penalties or expenses arising from legal, tax or accounting compliance issues and any incidental, punitive, exemplary or special loss, damage or expense.',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: 'Our total aggregate liability to you under these Terms and in connection with Employment Hero Rewards is limited to the value of any Rewards earned in the 6 month period (or part thereof) prior to the liability arising. ',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: 'You may have the benefit of non-excludable warranties, guarantees or other rights provided under applicable laws in your jurisdiction (“Non-excludable Conditions“). These Terms are subject to any Non-Excludable Conditions that apply to you. Our liability for a Non-excludable Conditions is limited, at our option, to the cost of replacing or paying for the costs of replacing the relevant goods or services (except if the liability for any Non-excludable Conditions cannot be so limited by law, in which case our liability for that Non-excludable Condition will be limited to the extent permitted by law).',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: '19. NOTICES',
    textVariant: 'small-bold',
    type: 'text',
  },
  {
    text: 'We will send all notices and other communications regarding Employment Hero Rewards to you at the email address or physical address provided with your Account. You may provide notices to us, by visiting our Contact page.',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: 'A notice, consent, information, application or request is to be treated as given or made at the following time:',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: 'if it is delivered, when it is left at the relevant address.',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: 'if it is sent by post, three (3) business days after it is posted.',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: "if it is sent by email, as soon as the sender's information system sends the email to the recipient's email box provided that the sender does not receive a message sent by the recipient's information system advising the sender that the recipient has not received the email.",
    textVariant: 'small',
    type: 'text',
  },
  {
    text: 'If a notice, consent, information, application or request is delivered, or an error free transmission report in relation to it is received, on a day that is not business day, or if on a business day, after 5pm on that day in the place of the party to whom it is sent, it is to be treated as having been given or made at the beginning of the next business day.',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: '20. DISPUTE RESOLUTION',
    textVariant: 'small-bold',
    type: 'text',
  },
  {
    text: 'If a party considers that a dispute has arisen in connection with these Terms, then that party must give written notice to the other party setting out reasonable details of the nature of the dispute (Dispute Notice) within 7 days of becoming aware of that dispute.',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: 'Representatives nominated by each party will meet within 7 days of the date that the receiving parties receive the Dispute Notice and attempt in a good faith effort to resolve the dispute as quickly as possible.',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: 'If the nominated representatives are unable to resolve the dispute within 12 days of the Dispute Notice, then the parties may refer the dispute to mediation by a mediator agreed upon between them, or failing agreement, a mediator appointed by the Australian Disputes Centre or any body which replaces it',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: 'If the dispute is not resolved within 30 days of its reference to mediation or if a party refuses to comply with its obligations for mediation, then any party to the dispute may commence court proceedings.',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: 'Nothing in this clause 20 prevents a party from seeking an interim injunction at any time where it deems appropriate.',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: '21. Entire agreement',
    textVariant: 'small-bold',
    type: 'text',
  },
  {
    text: 'These Terms and our General Terms, constitute the entire agreement between you and us regarding Employment Hero Rewards and supersede and replace any prior agreements and communications between you and us, except as expressly set forth herein.',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: '22. Variation',
    textVariant: 'small-bold',
    type: 'text',
  },
  {
    text: 'We reserve the right to change, amend, modify, add or delete any of these Terms, at any time, in an exercise of our sole discretion. These amendments, modifications, additions or deletions apply to your use of Employment Hero Rewards as soon as they are live (whether or not you are aware of those amendments, modifications, additions or deletions) and will be notified to your Account by email after a change has occurred. Your continued use of Employment Hero Rewards following any changes to the Terms signifies that you accept and agree to the changes, and that all subsequent transactions and usage by you will be subject to the amended Terms.',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: '23. Assignment / Transfer',
    textVariant: 'small-bold',
    type: 'text',
  },
  {
    text: 'The rights given to you under these Terms are personal and you may not assign or transfer your rights or obligations under these Terms without our prior written consent. We may assign our rights and obligations under the Terms (in whole or in part) without your consent.',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: '24. Relationship',
    textVariant: 'small-bold',
    type: 'text',
  },
  {
    text: 'We are independent contractors. No agency, joint venture, partnership, trust, or employment relationship is created between you and us by way of these Terms.',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: '25. Severability',
    textVariant: 'small-bold',
    type: 'text',
  },
  {
    text: 'If any part or provision of these Terms is invalid, unenforceable or in conflict with the law, that part or provision is replaced with a provision which, as far as possible, accomplishes the original purpose of that part or provision. The remainder of these Terms will be binding on the parties.',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: '26. Waiver',
    textVariant: 'small-bold',
    type: 'text',
  },
  {
    text: "Except as otherwise set out in these Terms, a party may give or withhold an approval or consent to be given under these Terms in that party's absolute discretion and subject to any conditions determined by the party.  A party is not obliged to give its reasons for giving or withholding a consent or for giving a consent subject to conditions.",
    textVariant: 'small',
    type: 'text',
  },
  {
    text: 'The fact that a party fails to do, or delays in doing, something the party is entitled to do under these Terms, does not amount to a waiver of any obligation of, or breach of obligation by, another party.  A waiver by a party is only effective if it is in writing.  A written waiver by a party is only effective in relation to the particular obligation or breach in respect of which it is given.  It is not to be taken as an implied waiver of any other obligation or breach or as an implied waiver of that obligation or breach in relation to any other occasion',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: '27. Interpretation',
    textVariant: 'small-bold',
    type: 'text',
  },
  {
    text: 'In the interpretation of these Terms, the following provisions apply unless the context otherwise requires:',
    textVariant: 'small',
    type: 'text',
  },
  {
    text: 'Headings are inserted for convenience only and do not affect the interpretation of these terms;',
    textVariant: 'small',
    type: 'text',
    showListItemSymbol: true,
  },
  {
    text: 'A reference in these Terms to a business day means a day other than a Saturday or Sunday on which banks are open for business generally in New South Wales;',
    textVariant: 'small',
    type: 'text',
    showListItemSymbol: true,
  },
  {
    text: 'If the day on which any act, matter or thing is to be done under these Terms is not a business day, the act, matter or thing must be done on the next business day;',
    textVariant: 'small',
    type: 'text',
    showListItemSymbol: true,
  },
  {
    text: 'A reference in these Terms to dollars or $ means Australian dollars and all amounts payable under this document are payable in Australian dollars, unless stated otherwise;',
    textVariant: 'small',
    type: 'text',
    showListItemSymbol: true,
  },
  {
    text: 'A reference in these Terms to any law, legislation or legislative provision includes any statutory modification, amendment or re-enactment, and any subordinate legislation or regulations issued under that legislation or legislative provision;',
    textVariant: 'small',
    type: 'text',
    showListItemSymbol: true,
  },
  {
    text: 'An expression importing a natural person includes any company, trust, partnership, joint venture, association, body corporate or governmental agency;',
    textVariant: 'small',
    type: 'text',
    showListItemSymbol: true,
  },
  {
    text: 'Where a word or phrase is given a defined meaning, another part of speech or other grammatical form in respect of that word or phrase has a corresponding meaning;',
    textVariant: 'small',
    type: 'text',
    showListItemSymbol: true,
  },
  {
    text: 'A word which denotes the singular denotes the plural, a word which denotes the plural denotes the singular, and a reference to any gender denotes the other genders; and',
    textVariant: 'small',
    type: 'text',
    showListItemSymbol: true,
  },
  {
    text: "References to the word 'include' or 'including are to be construed without limitation.",
    textVariant: 'small',
    type: 'text',
    showListItemSymbol: true,
  },
  {
    text: '28. GOVERNING LAW',
    textVariant: 'small-bold',
    type: 'text',
  },
  {
    text: 'These Terms are governed by the laws of New South Wales, Australia and subject to the exclusive jurisdiction of the courts of New South Wales, Australia. ',
    textVariant: 'small',
    type: 'text',
  },
];
